### ISSUE TITLE
Are we doing direct commits to the code without PRs?

### ISSUE THREAD

**Issue by raovgarimella** [amanzi/amanzi#130]
Am I mistaken or are we directly committing changes to master without going through a PR? Asking what Amanzi's policy is. IMHO, code changes should always go through PRs as they allow other developers to be more aware of changes that are happening to the code and not be surprised by code changes.

**Comment by lipnikov** [comment]
Depends. If your commit is a small single commit and all tests passed, then a PR looks like a huge overhead.

**Comment by raovgarimella** [comment]
There is also the question of tests - once we get continuous integration put in place, a pull request can be checked automatically for a wide variety of compilers and settings before its merged. My suggestion is to make it a policy to go through a PR.

**Comment by lipnikov** [comment]
PR is a good policy when continuous integration is in place. Meanwhile, I am not willing to review PRs for small commits.

**Comment by ecoon** [comment]
That makes sense to me.  PRs also encourage currying multiple commits, which is also good practice.
