### ISSUE TITLE
Patch for MSTK shared-libs not working

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#138]
The patch for shared-libs in MSTK at 

https://github.com/amanzi/amanzi/blob/master/config/SuperBuild/templates/mstk-libs-shared.patch

doesn't work on my OSX, and I'm fairly sure can't work, as $MSTKLIB isn't yet defined at that point.  Can the patch be removed entirely?  I'm not sure what its intent was.  Removing the patch allows me to build successfully with static libs, but I haven't tried without it using shared libs.  If you don't have an OSX machine to test with shared libs let me know and I'll give it a shot.

**Comment by ecoon** [comment]
To be clear, the issue is that the patched cmake configure script fails, not that the patch itself fails!

**Comment by lipnikov** [comment]
Intend of this patch is to close all external dependencies during library linking. Probably for macports. Looks like MSTK upgrade changed names of some variables

**Comment by ecoon** [comment]
I don't have a macports-based machine to test with, but it is unnecessary for homebrew, static libs.  Is line 311 of https://github.com/MeshToolkit/MSTK/blob/v3_0_3/CMakeLists.txt not already doing this?

**Comment by lipnikov** [comment]
You may be correct. The new CMakeList.txt incorporated most changes made on the branch. I am testing the build without this patch on OSX. If everything is fine, two builds will be done in about 2 hours.
