### ISSUE TITLE
More general state and coupling while using the DAG

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#142]
State has some significant shortcomings in the current version.  Most importantly, it cannot hold anything that is not a CompositeVector, double, or Epetra_SerialDenseVector.  These limit the DAG to only the algebraic portions of the codebase.

Furthermore, ATS's concept of two States (one at the old time, one at the new) greatly limited flexibility within coupling.

This led Amanzi to basically abandon the DAG, and makes some things basically impossible in ATS (i.e. coupling explicit transport with subcycling to implicit flow, subcycling multiple implicit PKs, etc).  The downside from Amanzi's perspective is no use of the DAG.  Effectively Amanzi and ATS PKs cannot interact because of these limitations.

Daniil introduced the concept of a "tag" into State, which supports Amanzi's model of one State, with different tags (although initially Amanzi used different keys, not tags) to represent different time "locations" relative to a given time integration step.

A: This led to a conceptual redesign of State.  Requirements:
1. Store anything ("any" pointers)
2. Support tags.
3. Side effect -- allow arbitrary coupling schemes through tags.
4. Example Usage -- get Operators into the DAG
5. Example Usage -- get BCs into the DAG

Since this work touches nearly all of the codebase from State up, it also suggested a rewrite of the ugly (ATS) design that is the current hierarchy of PKs, Default PKs, Base PKs, MPC_PKs vs WeakMPCs vs MPC, etc.

B: Requirements on a new design for PKs include:
1. Support arbitrary coupling combinations, including subcycling.
2. Resolve the dual-view issue of TreeVectors (view for time integrators) vs CompositeVectors in State (view for the DAG) that is very confusing and very bug-prone if one isn't careful.
3. Example Usage -- get a PK whose primary data is a Struct (e.g. Vegetation) and not a CompositeVector into the PK tree.
4. Example Usage -- couple this PK to an implicit PK, where the struct PK is integrated explicitly through a fixed time, rule-based "Advance" while the implicit PK subcycles as needed to match the fixed timestep.  Veg + water.
5. Example Usage -- couple a suite of subgrid PKs, each on their own adaptive timestep, which syncronize at a larger, fixed step.

**Comment by ecoon** [comment]
More commentary coming soon -- work on this issue is progressing on branch "dev-new-state"

**Comment by lipnikov** [comment]
I am lost. Are you proposing to extend A using B?

**Comment by ecoon** [comment]
No.  A is a refactor of existing code, nearly all limited to src/state.  It would affect Amanzi's PKs significantly, because it changes the State interface significantly, but is a refactor in the sense that changes to Amanzi's PKs are syntactic more than semantic changes.  Many, but not all, can be done via sed or python or something similar.

Currently A is nearly done on the branch.  It isn't complete because, over time, more and more non-State functionality has been added to State, and I have removed that functionality from State.  It would have to be reimplemented elsewhere, but I wanted to get some of the core functionality in front of you all before I worried about the rest yet.  And State should be limited in scope as much as possible.  It's a big class already.

B is a rewrite of the PK interface and a rewrite of how ATS PKs are written.  Amanzi could adopt these, and if Amanzi intends to do more work coupling multi-physics problems, subgrid models, mutli-scale/multi-domain models, etc, I would recommend it.  But, just like Amanzi doesn't currently use the DAG or share PKs with ATS, it doesn't need to use these changes. 

B is more "in progress," but I have a prototype of B in the branch as well, which implements 3 ODEs using both Explicit and Implicit time integration, with and without subcycling, and couples them in various ways, from Weakly to Implicit/Explicit to Explicit+Subcycled Implicit to Global implicit, etc.

**Comment by lipnikov** [comment]
One pending PR significantly changes BCs and operators. It may affect step A5...

**Comment by ecoon** [comment]
I haven't touched those yet.  Does the PR affect the OperatorDiffusion, etc, interfaces?  Or just their implementation?  The evaluator should be agnostic to their implementation.

**Comment by lipnikov** [comment]
PDE-type operators were renamed: e.g., OperatorDiffusion -> Diffusion. A few interfaces were changed slightly to use Ptr.

**Comment by lipnikov** [comment]
State was refactored. If some work left in this ticket, it should be done under separate tickets.
