### ISSUE TITLE
bug in schemas and Accumulation

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#155]
The new PDE code has some cases such as:

https://github.com/amanzi/amanzi/blob/master/src/operators/PDE_Accumulation.hh#L89

where a Schema is generated from:
```
Schema schema;
schema.Init(schema.StringToKind(name));
```

I think this is a bit buggy, since schema.StrongToKind() returns a AmanziMesh::Entity_kind while schema.Init() expects either an int, which is then compared to ints like OPERATOR_SCHEMA_BASE_NODE, or an Entity_kind AND a number of vectors.

I'm guessing the correct code should be:
```
schema.Init(schema.StringToKind(name), 1);
```
and NOT do the implicit conversion from Entity_kind to int?  Not totally sure how these various enums interact (this would be much clearer if these were typed Enums instead of ints!)

At any rate, as is, 
```
schema.Init(schema.StringToKind("cell"))
```
returns a schema object including both FACE and CELL, which I'm fairly sure is a bug!

**Comment by ecoon** [comment]
Pushing a fix in a second but I'd like you to look at it @lipnikov

**Comment by lipnikov** [comment]
Works me. Thanks for fixing.
