### ISSUE TITLE
remove rel perm function requirement from Upwind

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#159]
The current upwind classes are not usable* by ATS because of the requirement that a function pointer Model::Value is provided, which evaluates the rel perm as a function of boundary condition Dirichlet data.  Instead I would like to remove that requirement, instead including a "boundary_face" component of the rel perm vector which includes the value (respectively derivative) of the rel perm function on boundary faces as a function of Dirichlet data where provided.   This would require the Flow PK to be updated to write these values into the vector.

Konstantin, are you ok with this?  As it currently stands, bc_values and the Value function are only used to evaluate the function against the value -- passing in the result instead meets all current use cases.  Are there any other use cases you have planned that this would be an issue for?

*rel perm is a function of temperature and pressure for ATS's Arctic applications

**Comment by lipnikov** [comment]
I see no potential issues with your suggestion provided that it works in parallel.

**Comment by ecoon** [comment]
The current unit tests appear to test this in both parallel and serial (operators_diffusion) and in user-space code (i.e. flow tests).  All of these still pass in serial and parallel.

I replicated the existing behavior in these changes, though there was some of it that was a bit fishy.  Specifically, using ghost faces from boundary conditions might have issues where boundary faces get tested by whether or not they have two neighboring cells that are USED.  An OWNED face with 1 USED cell neighbor is always a boundary face, but a USED face with 1 USED cell neighbor might not be a boundary face (it might be a domain-local boundary but not a global boundary).

**Comment by lipnikov** [comment]
Compute2 is seems unused. Should we keep it?

**Comment by lipnikov** [comment]
Q:  USED face with 1 USED cell neighbor might not be a boundary face...

A: Flag OPERATOR_BC_DIRICHLET is set up using boundary mesh sets. It should be correct  provided that mesh sets are correct. Hence, a code that verifies this flag will skip the case of 2 cells.

**Comment by lipnikov** [comment]
Your commit broke some transport tests. I guess we agreed to use pull requests for commits that can break the stable master branch.

**Comment by ecoon** [comment]
Apologies -- I ran these tests and missed the transport test failing.  It is failing for me as well, I just missed it.  What is the NS test?  And is this closable again with your fixes?

**Comment by lipnikov** [comment]
I think I fixed everything. On a positive side, I improved transports management of memory for BCs. NS=NavierStokes.

**Comment by ecoon** [comment]
Can we close this again now?  Just cleaning up house a bit while I wait on tests to compile...
