### ISSUE TITLE
Unintended merge of xsdk-0.3.0 branch breaks master

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#162]
The unintended merge of alexis/xsdk-0.3.0 branch breaks builds on the master.  Some options currently included in bootstrap.sh,  in conjunction with our HDF5_LIBRARIES struggle with -ldl dependency are likely to blame.   

This merge does update several TPLs as well, bringing us inline with xSDK 0.3.0 and nearly up to current development in PETSc and Trilinos.

**Comment by lipnikov** [comment]
MAster is stable.
