### ISSUE TITLE
shadowed index in beaker component loops

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#168]
Clang issues some warnings about some odd code in beaker -- can someone take a quick look and fix this?  I glanced at it, and the code is either inefficient or wrong or poorly documented (hopefully the first or third?)

I'd assume it is safe to change the second i to j, but didn't want to blindly do that without more carefully inspecting what was going on there.  Note these are in 0.87, but the same issue shows up in dev (same line numbers):

```
/Users/uec/codes/ats/amanzi/repos/0.87/src/common/chemistry/reactions/beaker.cc:1612:16: warning: declaration of 'i' shadows a previous local [-Wshadow]
       for (int i = 0; i < ncomp(); ++i) {
                ^
/Users/uec/codes/ats/amanzi/repos/0.87/src/common/chemistry/reactions/beaker.cc:1599:12: note: shadowed declaration is here
   for (int i = 0; i < ncomp(); i++) {
            ^
/Users/uec/codes/ats/amanzi/repos/0.87/src/common/chemistry/reactions/beaker.cc:1629:18: warning: declaration of 'i' shadows a previous local [-Wshadow]
         for (int i = 0; i < ncomp(); ++i) {
                  ^
/Users/uec/codes/ats/amanzi/repos/0.87/src/common/chemistry/reactions/beaker.cc:1622:12: note: shadowed declaration is here
   for (int i = 0; i < ncomp(); ++i) {
            ^
```

**Comment by lipnikov** [comment]
The code is fishy, especially around line 1629.

**Comment by lipnikov** [comment]
Looks like the second for-i-loop should be omitted in both cases.

**Comment by lipnikov** [comment]
David, this is a part of nonlinear solver, so you must be the expert too.
