### ISSUE TITLE
Standardize Section and Subsection headings in test documentation.

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#179]
The tests are documented with restructured text (rst), and should use a consistent layout of Sections and Subsections.   The current layout is 

**Test Name/Title**

- Capabilities Tested
- Background
- Model
- Problem Specification
  - Schematic
  - Mesh
  - Variables
- Results Comparison
- References
- About

**Comment by johnportiz14** [comment]
Create individual _Issues_ for each verification test (#226 - #239). Standardize section headings is included as checklist items for each _Issue_ now where appropriate.

**Comment by lipnikov** [comment]
David asked me to revisit infiltration tests.  This required to clean out Python scripts and fixed CCSE bugs. Here is the summary of recent changes:

1. Upgraded all amanzi*.py files. Python scripts for 1D cuts in x and z directions were moved to tools/testing. Copies were removed from python files inside regression tests. Names of python modules were extended with suffix "_1D", such as GetXY_[Amanzi|PFloTran|CrunchFlow][S|U]_1D.

2. A memory bug was patched in CCSE tools. TPLs should be rebuild. However, this code does not work for multiple materials, see later. Perhaps I do not understand clearly the code design behind multiple cuts across hierarchy of BoxLib  meshes.

3. Added figures to 3 infiltration problems: clay-sand, loan-sand, and sand-loam. Added these problems to the user guide. The same ccse tools return cuts with 2 points, ends of the first material. Something is still wrong with the Fortran code. I do not plan to dig now into this old code and disconnected plots for AmanziS for infiltration tests. Probably, upgrade to recent CCSE package should be considered seriously if they fixed the graphics there.

4. Renamed files amanzi*.xml to amanzi*-u.xml in few to match with structured.
