### ISSUE TITLE
Parallel bug in new TI schemes for transport PK

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#180]
Parallel bug in new TI schemes for transport PK: 4 cores, 100x100 mesh, diagonally moving box plume.

**Comment by dasvyat** [comment]
amanzi-0.87 has parallel bug branch for 

 <ParameterList name="transport">
      <Parameter name="spatial discretization order" type="int" value="2"/>
      <Parameter name="temporal discretization order" type="int" value="1"/>
      <Parameter name="cfl" type="double" value="2.99999999999999989e-01"/>

Although, this option is possible via native spec only.
