### ISSUE TITLE
superlu not picked up in FindAmanzi

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#199]
commit: 7f17b29bfbe2b9718baa04d3a11e98714a3404f7
Introduced a bug in that find_package(amanzi) no longer picks up the necessary libraries to link Amanzi libraries, namely it does not pick up the necessary superlu and superlu_dist libaries in the dependencies.

ATS uses find_package(amanzi) read in AmanziConfig.cmake, which is installed by Amanzi.  In that file, through some black magic in AmanziTargets and Amanzi_ENABLED_TPLS, Ifpack libraries are included in link_libraries, which then recursively through more black magic links in Hypre libraries, but NOT SuperLU libraries.

If Amanzi is adding SuperLU as a dependency to HYPRE, and since HYPRE doesn't provide a FindHypre to set up that dependency, Amanzi needs to make sure SuperLU is included as a linked library.

Hopefully something in there made sense to you, because it didn't to me.

**Comment by ecoon** [comment]
This is not a problem on my laptop, so don't think too hard on this yet... possibly just need to better nuke TPL/Amanzi/ATS installations and try again fresh.

**Comment by jd-moulton** [comment]
I'm not sure why you need to clear PR #195 to test? 

 It would be good to track down whether or not PETSc starts this bad ordering or if it is coming from somewhere  else.   I should have some time tomorrow to look at some builds.

**Comment by lipnikov** [comment]
Confirmed with MPICH-3, gcc-7, and static libs. Simple solution is to move amanzi_solvers libraries to the end of the list of Amanzi libraries. 

Possible explanation. libpetsc.a was added to the list of link libraries by CMake. Since this imported library does not have dependencies, no other libraries were added.

**Comment by ecoon** [comment]
Where did you reorder the amanzi libraries?  ATS's src/executables/CMakeLists.txt?  Or somewhere else?

**Comment by lipnikov** [comment]
I reordered the list of amanzi libraries in ATS' src/executables/CMakeLists.txt

**Comment by ecoon** [comment]
Yeah, I tried that first, and it doesn't change the order for me.  I'm a bit surprised to does for you, since all of amesos, superlu, and hypre appear in amanzi_solvers and in nothing else.  Though I'm not using PETSc in these builds, which would use superlu and hypre but not amesos and therefore might change the order.

**Comment by lipnikov** [comment]
Please attach your AmanziTargets.cmake. HYPRE_LIBRARIES has 5 libraries in Amanzi.  Did you build new Amanzi libs from scratch?

**Comment by lipnikov** [comment]
TPLs build scripts were updated. I do not see this issue on my Mac.
