### ISSUE TITLE
seacas attempting to install in /usr/local

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#200]
Contents of: /software/user_tools/current/cades-ccsi/ats/amanzi-tpls/build-dev/RelWithDebInfo/gcc-5.3.0_openmpi-1.10.3/seacas/seacas-timestamps/seacas-install-err.log

```
Install the project...
/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cmake/3.8.2/centos7.2_gnu5.3.0/bin/cmake -P cmake_install.cmake
-- Install configuration: "RELEASE"
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/local/lib/cmake/SEACASProj.  Maybe need
  administrative privileges.


make: *** [install] Error 1
```

after bootstrap.  More when I get to work and try to fix this.

**Comment by ecoon** [comment]
This might be user stupidity.

**Comment by ecoon** [comment]
```
if [ ${ATS_BUILD_TYPE} == Debug ]
then
    dbg_option=--debug
elif [ ${ATS_BUILD_TYPE} == RelWithDebInfo ]
then
    dbg_option=--relwithdebinfo
else
    dbg_option=--opt
fi

echo "Running Amanzi Boostrap with:"
echo "  AMANZI_SRC_DIR: ${AMANZI_SRC_DIR}"
echo "  AMANZI_BUILD_DIR: ${AMANZI_BUILD_DIR}"
echo "  AMANZI_INSTALL_DIR: ${AMANZI_DIR}"
echo "  AMANZI_TPLS_BUILD_DIR: ${AMANZI_TPLS_BUILD_DIR}"
echo "  AMANZI_TPLS_DIR: ${AMANZI_TPLS_DIR}"
echo " with build type: ${ATS_BUILD_TYPE}"
echo ""

${AMANZI_SRC_DIR}/bootstrap.sh \
   ${dbg_option} \
   --with-mpi=${OPENMPI_DIR} \
   --enable-shared \
   --disable-structured  --enable-unstructured \
   --disable-stk_mesh --enable-mstk_mesh \
   --enable-hypre \
   --enable-silo \
   --enable-physics \
   --amanzi-install-prefix=${AMANZI_DIR} \
   --amanzi-build-dir=${AMANZI_BUILD_DIR} \
   --tpl-install-prefix=${AMANZI_TPLS_DIR} \
   --tpl-build-dir=${AMANZI_TPLS_BUILD_DIR} \
   --tpl-download-dir=${ATS_BASE}/amanzi-tpls/Downloads \
   --tools-download-dir=${ATS_BASE}/amanzi-tpls/Downloads \
   --tools-build-dir=${ATS_BASE}/build \
   --tools-install-prefix=${ATS_BASE}/install \
   --with-cmake=/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cmake/3.8.2/centos7.2_gnu5.3.0/bin/cmake
```

**Comment by ecoon** [comment]
I'm not able to repeat this when building on a compute node.  I think my filesystem is doing wierd things here...

**Comment by lipnikov** [comment]
I think SEACAS is misconfigured. SuperBuild missed some options. Can you attach wrong pieces of seacas-173a1e6-build/CMakeCache.txt

**Comment by ecoon** [comment]
Did this get reopened by mistake?  Seacas looks correctly configured to me at this point, I'm not sure why it was getting incorrectly configured in my first attempt.  Are you seeing something weird in your builds?

**Comment by lipnikov** [comment]
I re-opened it to discus some issues with Build_SEACAS, in particular line 
-DCMAKE_INSTALL_PREFIX:FILEPATH=<INSTALL_DIR>
Do you know what the angle brackets mean in this file?

**Comment by ecoon** [comment]
https://stackoverflow.com/questions/13415222/variables-with-angle-brackets-in-cmake-scripts

suggests it really is just a plain string.  It must be a template pattern, that gets filled by the call to ExternalProject_Add (e.g. line 152).

Surely there is a better way to do this though?

**Comment by lipnikov** [comment]
I saw this before. There is no reference in cmake language for using <> in scripts. I am giving up. Close the ticket if u want.

**Comment by ecoon** [comment]
Right, it's not a cmake thing but a string literal.  To the configure's cache file it adds the line:

-DCMAKE_BUILD_DIR=<INSTALL_DIR>

Then later, the call to ExternalProject_Add() (whatever that function is) must do a template filling process, effectively

sed "s^<INSTALL_DIR>^/path/to/your/cmake_install_prefix^g" on that cache file.  Or at least that's the only thing I can come up with that would replicate the results I see in my cache.
