### ISSUE TITLE
Remove EvaluatorSecondaries and add EvaluatorSecondoryMonoType

### ISSUE THREAD

**Issue by dasvyat** [amanzi/amanzi#211]

**Comment by ecoon** [comment]
In progress... first I'm merging master to dev-new-state

**Comment by ecoon** [comment]
merged, starting work now

**Comment by ecoon** [comment]
I think this is working now -- didn't close it because it also required a cherry-pick of a commit from master.

**Comment by ecoon** [comment]
This makes the Evaluate_ and EvaluatePartialDerivative_ methods a bit clunky for secondary variable evaluators that only have one output (i.e. old-style Secondary, not Secondaries).  It may be easier to simply add a second, overloaded Evaluate_() method which simply calls the one with only a CompositeVector argument -- then the existing Evaluate_() methods can co-exist with the new one.

**Comment by lipnikov** [comment]
State was refactored... closing as outdated.
