### ISSUE TITLE
exterior_face_map

### ISSUE THREAD

**Issue by dasvyat** [amanzi/amanzi#213]
Currently exterior_face_map with ghosted entities includes both boundary and internal (ghosted) faces.
Probably it was easier to implement, but I don't think it aligns with owned-ghosted relationship for other entities. In particular, ghost mapping contains entities which are not belong to "owned" mappings on other
processes ( or the union of all ghost mapping is not equal to the union of all owned mappings).

**Comment by ecoon** [comment]
Um, that's definitely a bug, not laziness.  The current check for this map generation (Mesh_MSTK.cc e.g. line 3678) is "does the face have two regions or only one", and clearly this includes faces that are in the interior but on the "boundary" of the subdomain (including ghost cells).  

I believe the only fix to this would be to add a MSTK tag to the owned boundary faces, then communicate that tag to update ghost cells.  I'm pretty sure Eugene knows how to work with MSTK tags and communication -- either he or Rao could probably do it fairly quickly.

**Comment by dasvyat** [comment]
I've already did it in the external_map branch of Amanzi. It was essential for NLFV to work correctly in parallel. You can look and comment on related pull request.

**Comment by lipnikov** [comment]
The issue was resolved.
