### ISSUE TITLE
Rename Explicit_TI_FnBase::Functional()

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#218]
I would like to rename Explicit_TI_FnBase::Functional() to something else.  Effectively I want to have a PK that satisfies both the Explicit_TI_FnBase and BDF_FnBase interfaces, and the clash between their Functional() methods means you can't inherit across classes that implement one but not the other (see below).  They do different things -- one calculates a functional to be minimized (BDF_Fn), which makes sense to me.  The other calculates a time derivative.

Previously I thought we had Dudt?  I'm fine with that, though I'm fine with other suggestions as well (hence this ticket).  Do you have a preference in names, or is Dudt ok?

----

If we have the following inheritance:

C --> B --> A

where B::Functional(t, y, dydt)
and A::Functional(told, tnew, uold, unew, f)

then calling C::Functional(told, tnew, uold, unew, f) does not compile.

**Comment by lipnikov** [comment]
FunctionalODE

First, Dudt is confusing in my opinion in context of multi step Runge  Kutta schemes. Second, ODE community uses often y for u and k for dt. So word-based name would be better.

**Comment by ecoon** [comment]
I'm not sure I like FunctionalODE though -- solving an ODE implicitly also requires a Functional to be minimized of the form in BDF_FnBase.

Maybe TimeDerivative()?  Or are you opposed to Time as well?

I'd hate to resort to ExplicitFunctional() and ImplicitFunctional(), but I guess that could work too?

**Comment by lipnikov** [comment]
How about FunctionalTimeDerivative for Explicit and FunctionalResidual for Implicit?

**Comment by ecoon** [comment]
Sounds good thanks
