### ISSUE TITLE
Verification Test: Transient One-Dimensional Confined Flow to a Pumping Well (Theis)

### ISSUE THREAD

**Issue by johnportiz14** [amanzi/amanzi#230]
- [x] Add rest of radii results to output table in **Results and Comparison**.
- [x] Make page title and TOC header match (discrepancy b/w 1D or 2D).
- [x] Standardize **Capabilities Tested**.
- [x] Add description in **Capabilities Tested**.
- [x] Fix **Model** description, (move current contents to **Background?**).
- [x] Add **Mesh** diagram.
- [x] Add units to **Variables**.
- [x] Fix math formatting in **Variables**.
- [x] Change plot legend order in **Results and Comparison**.
- [x] Add **References**.
- [x] General typos.

**Comment by daniellivingston** [comment]
![image](https://user-images.githubusercontent.com/20751300/73886569-216df480-4827-11ea-9b13-c4e001d3c886.png)

@johnportiz14 just to clarify for "Change plot legend order in Results and Comparison", is the issue that colors between scatter & lines don't match?

**Comment by johnportiz14** [comment]
I believe so, yes @daniellivingston, although I do think at one point the order of radii may not have been ascending. Otherwise, the drawdown lines do seem to match the corresponding radii.
