### ISSUE TITLE
Inconsistence file name in test directories of branch:master

### ISSUE THREAD

**Issue by quang-ha** [amanzi/amanzi#241]
Currently at master, inside `amanzi/testing/verification/flow/richards/steady-state/infiltration_clay_sand_1d/CMakeLists.txt` reads:

```
add_amanzi_comparison_test(infiltration_clay_sand_1d_u
                           INPUT amanzi_infiltration_clay_sand_1d-isv2.xml
```
in which the file `amanzi_infiltration_clay_sand_1d-isv2.xml` does not exist there - `master` has `amanzi_infiltration_clay_sand_1d-u.xml` and `amanzi_infiltration_clay_sand_1d-s.xml` only at the moment. This will fail if users build `amanzi` on `master` with `test_suits` and `reg_tests` on. 

The file `amanzi_infiltration_clay_sand_1d-isv2.xml` does exist under `amanzi-0.87`, so I don't know if it's the `CMakeLists.txt` that should change or the filename. This is similar for several other `testing` directories.

**Comment by jd-moulton** [comment]
Thanks for pointing out this inconsistency.   The regression testing capability was never completed, but will be addressed this month.   In this case, the name of the new input file is correct, and the CMakeLists.txt file needs to be updated to be consistent with the new convention.   I'm traveling but will update this as soon as I get back (Thursday).  If you have time and are motivated you could create a pull request with updated CMakeList.txt files.

**Comment by quang-ha** [comment]
agree with @lipnikov - I have been trying to fix the Python files as well - else `ctest` will issue `BAD COMMAND` when doing `make test`.

**Comment by quang-ha** [comment]
@jd-moulton Progress is being made at `https://github.com/quang-ha/amanzi/tree/quang/fix-CMakeLists`, but I am still unsure about the output of input files `${test_case}-s.xml` - as far as I can tell for example  `amanzi_infiltration_clay_sand_1d-s.xml` doesn't specify examples, so doing an observation comparison test wouldn't work...
