### ISSUE TITLE
unused code result in Mesh.cc

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#265]
Is there a reason for the loop starting here?

https://github.com/amanzi/amanzi/blob/master/src/mesh/Mesh.cc#L692

It looks like this might be copy-paste code that either missed a line or shouldn't have been included.  The result of the loop is a variable, dir, which is not used.  So either we missed applying dir to the normal or the dir is not needed and the loop should be removed.

**Comment by lipnikov** [comment]
Mesh classes were refactored.
