### ISSUE TITLE
Clean up bibtex data file (ascem.bib)

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#270]
The old system used several subdirectories to organize separate bib files by subject area.  These files were than concatenated into a single ascem.bib file that the theory guide (and other documents) can use.  This has a few errors in it, and better tools are available.   Ultimately, we need something that allows the documents and their citation data to be kept in something like Mendeley, and then exported to bibtex.  A cleanup and maintenance step using something like JabRef is likely needed before the bibtex file is ready for use.   

Automating this process would be best, but best to start with a quick cleanup of ascem.bib.

**Comment by Vitaliy-Gyrya** [comment]
JabRef is available on all platforms.

It maintains a database of entries with appropriate tools (search, sort, etc.). Hence, it is easy to catch duplicates and maintain the same format for all entries.

Multiple .bib files lead to the duplicate entries (with different keys).

________________________________

**Comment by Vitaliy-Gyrya** [comment]
Merged duplicates:
- bear1972dynamics to bear-1972
- IBabuska_JTOden_JKLee_1976a to IBabuska_JTOden_JKLee_1977a
- neuman1990universal to neuman_1990
- NilssonGerritsenYounis:2005 to NilssonGerritsenYounis:2005a

Is 'schaap2001computer' missing a name of the program?
