### ISSUE TITLE
Consistency of notations across sections

### ISSUE THREAD

**Issue by Vitaliy-Gyrya** [amanzi/amanzi#273]
1. There are some inconsistencies in notations between sections.
Sections "Isothermal flow", "Thermal flow" and "Transport" use the term liquid and hence subscript 'l'.
Section "Biochemical reaction processes" uses terms water and aqua and hence superscripts 'w' and 'a'.
I suppose for chemistry it is important that liquid is water. So I am not sure what to do about this inconsistency.

2. Section "Isothermal flow" uses subscript 'm' for matrix. In section "Thermal flow" instead of 'm'(?) there is index 'r' for rock, e.g. internal energy and temperature of the rock. Is this an inconsistency or do they refer to different entities, i.e. voids in rock vs rock itself?

**Comment by lipnikov** [comment]
Matrix refers to voids in rock. Rock could be replaced with a solid phase. I think we should use w, g, and s. If we ever add another phase, if may go as l or n.

**Comment by lipnikov** [comment]
Theory branch has been merged into master.
