### ISSUE TITLE
Create keys for state variables

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#277]
Hide explicit names of state fields in keys. This allows us to couple PKs that use the same names for state fields but live on different meshes.

**Comment by ecoon** [comment]
For what it is worth, if you're touching this everywhere now, you might consider changing these to calls of `Keys::readKey()` which allows you to set these from a parameter list.  This probably wouldn't be used by Amanzi for many things, but when you want to change the name of something to allow it to be used in another problem it comes in very handy.   For instance, doing surface transport using a transport PK intended for the subsurface requires providing a porosity right now.  By using `Keys::readKey()` and setting in the parameter list, "porosity key"="ponded depth" allows you to calculate mass of C and updated fluxes without changing anything else.  Just a suggestion though, feel free to ignore it.

**Comment by lipnikov** [comment]
I am leaning towards healthy separation of work between the converter and PKs. Converter should delegate most work to PKs. Frequent usage of readKey() puts more load on the converter to create a proper native XML. I think readKey() should be used very selectively, like in your example, but not for many fields.
