### ISSUE TITLE
Modify mesh constructor to provide more control parameters

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#282]
New features require more mesh control parameters. They must go through a parameter list. The easiest solution is to change one mesh constructor from 

   Mesh_MSTK(const char *filename,
             const Epetra_MpiComm *incomm_,
             const Teuchos::RCP<const AmanziGeometry::GeometricModel>& gm = Teuchos::null,
            const Teuchos::RCP<const VerboseObject>& verbosity_obj = Teuchos::null,
            const bool request_faces = true,
            const bool request_edges = false,
            const Partitioner_type partitioner = PARTITIONER_DEFAULT);

to 

Mesh_MSTK(const char *filename,
             const Epetra_MpiComm *incomm_,
             const Teuchos::RCP<const AmanziGeometry::GeometricModel>& gm = Teuchos::null,
            const Teuchos::RCP<const Teuchos::ParameterList>& plist = Teuchos::null,
            const bool request_faces = true,
            const bool request_edges = false);

**Comment by raovgarimella** [comment]
Also see refactoring of MeshFactory in Jali to make it easier to specify options

https://github.com/lanl/jali/blob/master/src/mesh/mesh_factory/MeshFactory.hh

**Comment by dasvyat** [comment]
Will this change interface to Amanzi::AmanziMesh::MeshFactory? If not, changes to ATS will be pretty minor (maybe no changes will be required at all).

**Comment by lipnikov** [comment]
Mesh factory changes constructor from

MeshFactory(const Epetra_MpiComm *communicator,
const Teuchos::RCP<const VerboseObject>& vo = Teuchos::null);

to

MeshFactory(const Epetra_MpiComm *communicator,
const Teuchos::RCP<const Teuchos::ParameterList>& plist = Teuchos::null);

**Comment by lipnikov** [comment]
BTW, constructors of structured meshes will be modified similarly, i.e. VerboseObject -> ParameterList

**Comment by ecoon** [comment]
yes please.  Really would be nice to clean out some of the existing constructors if they aren't used -- the traits/frameworks/constructors explosion makes it fairly labor intensive to maintain because every change shows up in 20 places.  Thanks for the heads up.
