### ISSUE TITLE
clean up Mesh constructors

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#284]
In commit bbc646113eb810ca312f9c9107ee26df447fb3a9, Konstantin did some cleanup of the mesh construction procoess.  But there is a lot more work that could be done there.

Right now we have 4 frameworks (3 of which work), with 7? constructors:

* read from file
* generate 2D
* generate 3D
* generate from GenerationSpec
* extract from reference to mesh and setnames
* extract from pointer to mesh and setnames
* extract from reference to mesh and set IDs

Logically there are really only three ways to construct, however: read, generate, or extract.

So most of these overlap and are small variations on each other.  

Furthermore, to change a constructor interface requires touching all four frameworks (which declare all constructors, but may not actually implement them), plus a "bogus_mesh" framework, plus both a create() and operator() method in the factory which just call each other, plus multiple methods in the traits implementation (four templated versions and one non-templated versions).  I believe that EACH constructor's interface definition actually appears 12 places.

So, at this point, there are three potential places to put logic about construction of a Mesh:

1. in the user's code (for instance, force the user to parse the generate parameterlist)
2. in the factory
3. in the framework's constructors

Right now we provide a rich interface in the factory (so little logic is required in user-code, good!), use the factory to choose a framework, and have many constructors.  These constructors then parse their arguments and call an internal, private Init_() method to do the actual construction.

I'm fairly sure, however, that the logic to go between, for instance, the "generate from GenerationSpec" constructor and the "generate 3D" constructor are common to all mesh frameworks.  Same for going between set names and entity ID lists.  This logic should live in one and only one place.

I believe we should be able to get down to at fewest 3, and and most 4 constructors for each mesh framework:

* read from file
* extract from Entity_ID_List

and EITHER:

* generate from GenerationSpec

OR

* generate 2D 
* generate 3D.

Then we can have our same rich interface for our factory but have many fewer constructors in the mesh.  My sense is that using the GenerationSpec is a good design idea, because it is much more extensible, but I would argue that instead of using the GenerationSpec, we should just use a ParameterList directly.  But this would also break a lot of tests, so I'm open to having 4 direct constructors in each mesh and calling one of these four from many different factory methods.

In addition to just the software maintenance disaster that is managing all of these constructors, we have a compile-time traits implementation that is either broken or used incorrectly.  Nominally the point of having traits is to ensure that, at compile time, if a class doesn't provide the trait, it doesn't need to implement that part of the interface.  Simple and other mesh frameworks that don't provide all of the constructors still stub out the constructors and then throw errors.  The whole point of traits is that they shouldn't have to -- I don't know if the traits stuff is broken or if it is just incorrectly used, but it sure isn't saving us work at this point.  It just is making it much harder to understand which mesh framework can do what.  I think it should just get ripped out and put that logic into the Factory.

Note it should also be possible to introduce two levels of Factory -- one which deals with providing a rich set of methods for making meshes and one which deals with picking the right class based on its implementation and the user's preference.

**Comment by ecoon** [comment]
I did some of this in a pull request coming soon, which also standardized the use of Comm (see #283 ).  More can be done, and I'll try to keep going with this a bit, but I wanted to get your thoughts Konstantin.

**Comment by ecoon** [comment]
Adding Rao as well, I think he is on board with this since he already ripped out all of the traits stuff in Jali.

**Comment by raovgarimella** [comment]
In Jali, I got rid of the template meta programming in the mesh factory and made setter-getter methods for various mesh constructor options. In my opinion, this is a nice clean mechanism. I would encourage Amanzi to adopt this method (even if it means short term pain).


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by lipnikov** [comment]
I agree with Ethan: we need to reduce the number of constructors and perform general clean-up of the framework. We did multiple re-factories of other tools, time to do it for the Mesh classes. If Framework could be merged with the Factory, it would be great for code readability and maintenance. I still support MOAB, but I think that STK is dead and the related code should be removed.  I am at a conference, so go ahead with PR.

**Comment by ecoon** [comment]
On mesh generation, do you have a strong preference of:

* two constructors, one for 2D, one for 3D
* one constructor using GenerationSpec?

**Comment by lipnikov** [comment]
Many tests do not use xml input, so I prefer 2 constructors. But it is also possible to create a macro for tests to have a short syntax. So I flexible.

**Comment by lipnikov** [comment]
I would also deprecate operators if there is a consensus

**Comment by ecoon** [comment]
I already took them out and updated all the tests to use create().  My sed-fu has been improving greatly over the last few days -- sed -E is magic.

**Comment by ecoon** [comment]
The only reason to prefer GenerationSpec would be if we thought there might be other generation options that we didn't want in the (optional) ParameterList.  I'm leaning toward two as well, preferring to put other (control flags, etc) in the ParameterList argument instead (like you did for "partitioner" options).

**Comment by raovgarimella** [comment]
Just in case the Jali code repo is not widely known, it is


https://github.com/lanl/jali


I am working on meshconvert issues in my spare time and have to soon devote my full attention back to my primary projects and so I am not too engaged in this process. I would like to have the two interfaces be close to each other so that if we switch to using Jali at some point, it will be without much pain. There are some useful things in Jali that would be of value to Amanzi. Just a recommendation.


Rao


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by lipnikov** [comment]
Rao, how do you handle verbose output in Jail? In Amanzi::Mesh, we use VerboseObject.

**Comment by raovgarimella** [comment]
I believe I got rid of that temporarily in Jali. Basically, I removed all Teuchos stuff


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by ecoon** [comment]
Yeah, I considered trying to do the switch to Jali now.  A few things kept me from doing so, but mostly it was the lots of extra stuff for wedges/tiles/etc and the lack of support for columns and deformation that we have extensive stuff for currently.

**Comment by raovgarimella** [comment]
Wedges, sides etc are optional and one can omit generating them. The other stuff is more time-consuming to resolve.


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by ecoon** [comment]
Also I'm going to redo AmanziMesh's cache soon anyway, which wouldn't play nice with Jali.  Effectively the mesh's cache will get moved into State to allow it to be generated on a CPU then stored on a device.

**Comment by raovgarimella** [comment]
Why would the Mesh stuff be in state? There may be better structural ways of resolving any issues you are facing.

________________________________

**Comment by ecoon** [comment]
If we want to use mesh geometry on a device (for instance, if we want to generate local matrices on a GPU, or evaluate water content, which is a function of cell volume), these quantities need to be on the device.  There are two solutions to this -- move Mesh to a device or move the cache to a device.  My current thinking is to keep the mesh object on the CPU only and put the cache into data structures that can be moved onto a device.

**Comment by raovgarimella** [comment]
Well, carrying Mesh_MSTK (or Mesh_MOAB) onto the device is ruled out - you would have to drag along Exodus, NetCDF, HDF5 libraries too. But I pause at the idea that they should be in the State class even though in a way you could argue that volumes, centroids, areas are mesh state. If I were doing it, I would explore the idea of a temporary Mesh class that one constructs for this purpose or a MeshHelper class that holds the cache.

________________________________

**Comment by ecoon** [comment]
Exactly on moving them to the device.  A MeshCache object is a reasonable idea.  But the MeshCache is going to effectively be a smaller version of State, that has to allocate memory on a device, manage views (and coherence) across device and CPU, etc.  All of this stuff is exactly what we'll be dealing with in State, so why not just put them in state? I'd still likely have a MeshCache object of some form, so that AmanziMesh doesn't need to be aware of State.  MeshCache would, in that model, manage moving data back and forth between Mesh and the cache in state.

**Comment by raovgarimella** [comment]
😞 on mixing mesh stuff in state.

BTW, In a project that I am working on (https://github.com/laristra/portage) we did some very interesting things with CRTP to statically construct a Mesh class that had the native mesh functionality in it and added some extra functionality common to all classes. For example, the basic native class would provide cells, faces, nodes and we would construct a class that got that info directly from the native class and added sides, wedges, corners etc. -- all without inheritance!! I hope that will also make it into Jali and Amanzi sometime.
________________________________

**Comment by ecoon** [comment]
I'm listening.  I don't understand why you're down on putting the mesh cache in state.  The mesh's job is to do topology and geometry.  State's job is to provide managed, generic access to data in a format that fits the performance needs of the simulation.

Mesh cache is effectively doing the job of State, for a Mesh.  Why require more places implementing the same things?

**Comment by lipnikov** [comment]
Do I understand correctly that Mesh would depend on State when cache is relocated?

**Comment by raovgarimella** [comment]
Because thinking of the state manager as managing fields on a mesh and the mesh manager as handling all geometric discretization related quantities is a nice elegant division of code functions. Using a MeshCache maintains that nice division. I am worried that if we cache mesh related variables in State, we will be tempted to cache not only volumes and centroids but also topological data there.


I do agree that this is a bit subjective (isn't most code design?) and unfortunately, I don't have the time to focus and offer up a more detailed solution.


________________________________

**Comment by lipnikov** [comment]
To get heads up. DG is the global duscretization, the class variable keeps data across the mesh like mesh cache. Should I also plan for moving this data to State ?

**Comment by ecoon** [comment]
Stopping this conversation now to start elsewhere in a new ticket.
