### ISSUE TITLE
Debug versions of TPLs

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#286]
Debug versions of TPLs do not build if MOAB is built.  

Specifically MOAB does not recognize that HDF5 should exist as libhdf5_debug.a, not libhdf5.a.

**Comment by ecoon** [comment]
I did a quick fix of this by linking libhdf5.a to libhdf5_debug.a.  But doing this might further confuse FindHDF5, and cause it to think we have BOTH debug and optimized builds of HDF5 available.  Doing this then (maybe only this?) caused FindHDF5 to tell us that our HDF5 libraries were:

```
HDF5_C_LIBRARIES = optimized libhdf5.a debug libhdf5_debug.a
```

In this line, "optimized" and "debug" are keywords in their library interface, e.g. 

https://stackoverflow.com/questions/5497348/debug-and-release-library-linking-with-cmake-visual-studio/5497425

Nominally this is smart -- it lets both libraries coexist, and lets cmake be smart enough to pull the right one for the right build on demand.  But it doesn't seem like these keywords can be passed in, at least not directly, to later calls, e.g. `set_target_properties(netcdf INTERFACE_LINK_LIBRARIES ...)` in FindNetCDF.  

So they have to somehow be stripped out at that point and resolved based on generater expressions (eg. https://cmake.org/cmake/help/v3.12/manual/cmake-generator-expressions.7.html )

I don't even pretend to understand cmake.

**Comment by ecoon** [comment]
In the meantime, I'm punting.  I don't really want HDF5 debug build.  I really just want to be able to build Trilinos in debug mode.  So I'm going to add some options to bootstrap:

```
--debug_trilinos
--debug_tpls
--debug
``` 

And a corresponding option to SuperBuild: `TRILINOS_BUILD_TYPE` which, if defined, gets passed to Trilinos configure.  This allows, for instance:  `--debug --debug_trilinos --relwithdebuginfo_tpls` which is a Debug build of Amanzi and Trilinos but a RelWithDebInfo build of the rest of the TPLs, which (at least for me) is the right amount of debug info for debugging Amanzi infrastructure.

**Comment by ecoon** [comment]
Maybe someone who understands cmake's INTERFACE stuff could fix a lot of this.  I'm not sure if our Find* are too old, too new, incompatible (we provide FindNetCDF but not FindHDF5, these should probably go together!) or what.

**Comment by lipnikov** [comment]
The logic was to replace only Find* that are weak or not portable in Cmake 3.8 or lower.
