### ISSUE TITLE
Finer control of  gravitational term in Darcy law 

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#289]
Diffusion equation has variety of forms in dispersive transport, flow in matrix, flow on fracture, etc:

\div(K \grad(u)) = q,
\div(K k \grad(u)) = q, 
\div(K k \grad(u + b g z)) = q,
\div(k \grad(u)) = q, 
\div(k \grad(u + b g z)) = q,

where K is a tensor, and k and b could be either constants, or space-time functions.  When k and b are constants, some optimization is performed in the code. It is done in two places, PKs and operators. We should always remember about this, especially when a new diffusion solver is added to the factory. The purpose of this ticket is perform optimization only inside the operator. 

Implementation-wise, we limit set up tools to the list below:
SetConstantCoefficient(K)
SetVariableCoefficient(K)
SetVariableCoefficient(k, dkdu)
SetConstantGravitationalTerm(b)
SetVariableGravitationalTerm(b, dbdu)
SetGravity(g)

Constants could be provided using the parameter list as well. Existing factories will be preserved.

**Comment by ecoon** [comment]
I approve of this change.  Unifying these has been an ATS nightmare at various points (constant rho, variable rho, etc etc), and we often end up providing one or more of these things as a vector filled with 1s.  Not specifying one or more of these things should be valid as well.
