### ISSUE TITLE
update SuperMap to be more general

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#291]
It has come up that there are three ways to have multiple degrees of freedom on the same entity in a SuperMap:

1. An Epetra_BlockMap with ElementSize > 1 (potentially variable!)
2. A CompositeVectorSpace created with num_dofs > 1
3. A TreeVectorSpace with more than one blocks.

SuperMap currently can handle either 2, or 3, but not both at the same time.  Furthermore, it breaks if it is created from two CompositeVectorSpaces that use the same component name to refer to different maps.  For instance, trying to combine surface cells with subsurface cells would be bad.

We ought to be able to, from just the maps provided, cover all three within SuperMap.

**Comment by ecoon** [comment]
The first is easy, it just requires care to use ElementSize() and FirstPointInElement().  The move from Epetra_Map to Epetra_BlockMap requires this, but we really ought to use it more often.  Frankly, if you want a pressure p + (u,v,w) flux, you would probably be better off writing it as a BlockMap, and not as a CompositeVector with num_dofs=3.  The former always lays things out as 

```(u0,v0,w0, ... uN,vN,wN)```

while the latter lays things out as three independent vectors that may not even be contiguous in memory until they are put in a SuperMap.  

The second two are more difficult because they are easy to mix up.  My sense is that the interface could easily be:

```
SuperMap::SuperMap(CompositeVectorSpace space); // num_blocks == 1
SuperMap::SuperMap(std::vector<CompositeVectorSpace> spaces); // num_blocks >=1
SuperMap::Indices(comp_name, dof_num, block_num);
SuperMap::Indices(comp_name, other) { 
  if (num_blocks == 1) { 
    return Indices(comp_name, other, 0);
  } else {
    return Indices(comp_name, 0, other);
  }
}
```

Here block_num refers to the index in the constructing vector, comp_name refers to whatever you called the component in the CompositeVectorSpace, and dof_num ranges from 0 to whatever the num_dofs provided in that CompositeVectorSpace's component.

Note that there is no expectation of the ordering here.  If you pass:

```SuperMap(  { CompositeVectorSpace("cell", CELL,1), CompositeVectorSpace("face", FACE,1) } );```

then `Indices("face", 0, 0)` will throw an exception, despite the fact that `Indices("face",0, 1)` would not.

There is also not necessarily an expectation of the maps.  If you pass:

```SuperMap(  {CompositeVectorSpace("cell", CELL, 1), CompositeVectorSpace("cell", FACE, 1) } );```

(note the intentional naming of two different maps by the same component name) it should still work.  

This fixes the requirement with the current implementation that TreeMatrix must only deal with block matrices that have the same schema in each block.  

It also fixes the requirement that if two components are named the same thing they must have the same map.

It makes explicit the difference between a single CompositeVector with num_dof > 1 and two CompositeVectors, each with num_dof==1.

I believe this should be as general as we are currently able to do (with the addition of BlockMap).

**Comment by lipnikov** [comment]
How is working on this ticket now?

**Comment by lipnikov** [comment]
SuperMap::Indices(comp_name, other) is probably not needed. It looks like a non-trivial overloading.

**Comment by ecoon** [comment]
I am working on it now, just grabbed a few things from your branch (updates to include Epetra_BlockMap in Block/CompositeVector/CVSpace, etc).

I think the best strategy is simply to put another layer on top of SuperMap.  SuperMap itself provides a clear role of managing the layout, but needs a wrapper for creating these things in a variety of ways for a variety of users.  Hopefully will set up a pull request tomorrow sometime, I'm about halfway done but today got busy with proposals.

The pull request will not be ready to merge -- it will need some more testing -- but consider it an early view of what this would look like.

**Comment by ecoon** [comment]
WIP here

https://github.com/ecoon/amanzi/tree/ecoon/supermap

**Comment by ecoon** [comment]
Ok, testing still in progress, but this is close to right. 

Effectively, SuperMap did not change except to convert Map --> BlockMap.  SuperMap still expects components to be lumped by Map.

SuperMapWrapper (name is open to discussion) wraps a SuperMap for use by operators.  It takes a list of CompositeVectorSpaces and merges the various components based on whether Maps are the same (component names do not matter).  It then provides the ability to get indices based upon:

```
SuperMapWrapper::Indices(int block_num, const std::string& compname, int dof_num);
```

These indices should handle (UNTESTED, tests still on the way):

- arbitrary element sizes (including variable)
- two CVs with different maps named the same thing (i.e. a CV for subsurface mesh and a CV for surface mesh, both with "cell" component names), or a fracture pressure + a matrix pressure
- two CVs with the same map named different things get squashed together
- NumVectors() in the CV > 1
- SuperMaps for creating TreeOperators with differing blocks.  E.g. NLFV energy + MFD pressure.

This should (once tested) allow fracture + matrix SuperMaps to be created, both using arbitrary number of face and cell unknowns and calling them the same component names (cell, face).  Using a SuperMapWrapper instead of a SuperMap, then calling Indices() or GhostIndices() to get the list of indices that map the BlockMap's Points into the SuperMap's indices should work.

**Comment by lipnikov** [comment]
Suppose I have two wells on two different meshes and both maps have local ids {1,2,3}. Will it work?

**Comment by ecoon** [comment]
Haha, you guys are going to have to turn some of these into tests for me to be sure.  

Theoretically this version of SuperMapWrapper should be able to handle any combination of non-equal, variably-element-size maps, cross any number of vectors within the CompositeVector component, cross any number of copies of that map both within that CompositeVector and in other CompositeVectors.  I think this is as general as we can currently make maps, we can put into SuperMaps in consistent ways.  But as I add tests, add some more!

**Comment by ecoon** [comment]
Effectively a SuperMap knows how to deal with unraveling and interleaving a "list of lists" ragged set of maps:

[ Map1 x N1 copies, Map2 x N2 copies, ..., MapM x N-M copies]

into a single Epetra_Map for use with a TreeOperator (mathematically a block matrix).

Map1 ... MapM may be equal, but probably they are not.  Then the points of those maps (I'm being careful to say points and not GIDs, because GIDs refer to Elements in a Map, while Points refer to entries in the vector) are interleaved, and ghosts are all at the end.

SuperMapWrapper then takes a list of CompositeVectorSpace (or equivalently a TreeVectorSpace) and deals with the mapping of this 3-level nested structure by lumping them (not by component name, as was in the old code) by Epetra_BlockMap::SameBlockMapDataAs(), and storing a block info map.

This map, called `block_info_` in the code, is from:

```
std::tuple< block_id, component_name, dof_num >  ---> std::pair<unique_component_name, lumped_dof_num>
```
In the former, `block_id` refers to which CV it comes from, or equivalently, which block in the block operator.  `component_name` refers to the component in that CV, and `dof_num` which DOF in that CV.

In the latter, unique_component_name is an arbitrary string generated as the name of the first component which had that map plus the block_id in which that map first appeared.  Any other time we see that map (be it as a second component in the same CV or as a component in a later CV) we lump it under that unique_component_name and add to the lumped_dof_num.

Users have no need to know the unique component name or lumped dof num.  They only need to know, I have N local Points, what N LIDs in the SuperMap do these points correspond to?  Then they can copy into/out of their vector, and assemble into the full matrix.

So while you CAN directly make SuperMaps, it is likely a better idea to make SuperMapWrappers and let that deal with the lumping for you.  If you don't want to lump (lumping makes it easier on preconditioners, etc) and know you have either n_dofs = 1 or n_CompositeVectors = 1, you can directly make a SuperMap safely and index it directly.

**Comment by lipnikov** [comment]
What if I do not want to interleave DOFs of identical maps for preconditioning purposes?

**Comment by dasvyat** [comment]
Have I understood correctly that SuperMapWrappers will be used everywhere in Operators instead of SuperMap? All detail how compute LIDs correctly will be moved to SuperMapWrappers?

**Comment by dasvyat** [comment]
What is the definition of identical maps? Is it just length or also partitioning and/or distribution among elements? I think we can allow to specify manually which components are identical and should be interleave. In this case even if they are identical, but user don't want them to interleaved he just don't mark them as identical.

**Comment by ecoon** [comment]
> Have I understood correctly that SuperMapWrappers will be used everywhere in Operators instead of SuperMap? All detail how compute LIDs correctly will be moved to SuperMapWrappers?

Yes, and sort of.  All detail of how to compute LIDs correctly are in SuperMap.  SuperMapWrapper just alters how the SuperMap is blocked/interleaved and packages it up.

> What is the definition of identical maps? Is it just length or also partitioning and/or distribution among elements? I think we can allow to specify manually which components are identical and should be interleave.

The definition of identical, for now, is `Epetra_BlockMap::SameBlockMapDataAs()`, which Epetra describes as "This is a very cheap check whether two maps are identical."  I didn't look at the Epetra source to see exactly what this means, but I assume that, at the least, it checks partitioning/distribution as well.  "Very cheap" suggests it doesn't communicate, however, so I'm not exactly sure.  There is also an `Epetra_BlockMap::SameAs()` which I know is not cheap.

I don't necessarily think it is a good idea to have the user specify what is and isn't identical.  This is what led to passing the multi_domain flag through tons of code.  This can only be known at a very high level, and depends on a ton of logic.  For instance, in a global implicit problem, it can only be known by the highest level strong MPC, which then must consider the discretizations of everything it is coupling,  the physics of everything it is coupling, and the "BlockMap-ElementSize" domain aspect of everything it is coupling, to know for sure whether and which maps are identical. Your rich set of examples makes it clear that such logic would be very hard to keep track of, let along communicate to the SuperMap object.  So I would much rather detect this sameness than force the user to specify it.

> What if I do not want to interleave DOFs of identical maps for preconditioning purposes?
>  In this case even if they are identical, but user don't want them to interleaved he just don't mark them as identical.

I don't really know why you wouldn't want to interleave everything you can.  Remember, the only reason we use SuperMaps is to assemble into a single vector and matrix to hand off to a preconditioner/solver/whatever from an external package.  There is currently no other use for SuperMap.  None of our LinearOperators use SuperMap (they use the forward Apply that is not assembled).  

Certainly the performance of Hypre is much better with interleaved -- interleaved allows the "number of functions" option to be used, which in tightly coupled systems results in ~an order of magnitude better performance.  Certainly the performance of any ILU(k) method is much better interleaved than not (as off-diagonals would never be within k rows of the diagonal).  I'm not sure it matters for other PCs, but it doesn't hurt other PCs, and I don't think it significantly impacts performance to do it.  (The only possible change in performance is if the interleaving causes a few more cache misses while copying a dense local matrix into a strided sparse matrix with really large block size, or maybe results in some SSE instructions not being used? I can't come up with any other way that it would change things.)

That said, it wouldn't be that hard to have a "policy" or enum to give SuperMapWrapper.  This could be something like:

enum struct InterleavePolicy { NONE, IF_BLOCKS_ARE_IDENTICAL, ALL};

or something where we could define a few options.  Setting what gets lumped/interleaved and what stays as separate blocks is one line of code, so having some options here is straightforward.

**Comment by ecoon** [comment]
Actually, one correction -- it may make sense for Operator.cc to use SuperMap directly.  An Operator's Domain and Range maps are CompositeVectorSpaces, and so have no "block_num", only component names and dof nums.  Eliminating the third dimension is a bit more natural, and it is unlikely that such a CompositeVectorSpace would have two components with the same map (Although maybe that isn't true, for instance one might have "cell" and "face" pressures, and "flux" for flux on faces.  Would you want to interleave flux and p on faces?  Maybe there is no advantage to that?)

So TreeOperator should use SuperMapWrapper, but Operator could use SuperMap directly or could use SuperMapWrapper.

Maybe this suggests a better name for SuperMapWrapper?  TreeSuperMap?  SuperSuperMap!  Just joking, but seriously, SuperMapWrapper isn't a great name.  I just don't have a better one.

**Comment by ecoon** [comment]
Is there a reason for both Operator methods (e.g. Operator::CopySuperVectorToVector) and nonmember functions CopySuperVectorToCompositeVector in OperatorUtils?  

It seems to me that one of these should go away, likely the member function ones?

**Comment by lipnikov** [comment]
"A wrapper is just some smallish class whose purpose is to provide a different interface than the thing it wraps." I think that this name is informative.

**Comment by lipnikov** [comment]
The original idea was to rely on the new schema than the structure of the composite vector space. The schema is the ordered list and is suppose to be aligned (not yet) with the structure of whetstone matrices for discretizations that use various degrees of freedom (on faces, at nodes, etc). But maybe all this is not needed for data copy...

**Comment by ecoon** [comment]
It's a good point that the ordering of the Whetstone local matrices is hard-coded in Operators, and assumed to be consistent with Whetstone's internal ordering.  Would the goal be to have the Schema be given by Whetstone to the Operator?

Either way, it would be straightforward to build a CompositeVectorSpace that was constructed from the Schema, or have a SuperMap factory function that took a list of Schemas and a mesh to generate the SuperMap across BlockOperators, each Block with its own Schema.  In ATS we don't assume that we know the CompositeVectorSpace of the primary unknown -- this is given by the Operator after it is constructed from its various PDE components, and pressure is constructed from that CVS.  Having the Operator, instead of building a CVS, build a schema, then construct the CVS from the schema and the SuperMap from the collections of CVSs or Schemas makes sense to me.

**Comment by lipnikov** [comment]
Precisely, each discretization method will eventually generate a schema.
