### ISSUE TITLE
XDMF output of polyhedral meshes is incomplete

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#319]
Currently, XDMF output of true polyhedral meshes is incomplete. Instead of cells, faces of cells are saved into a mesh file.

**Comment by 56th** [comment]
@lipnikov Thank you so much for the fix!

**Comment by lipnikov** [comment]
VisIt cannot process such meshes. Use Paraview.

**Comment by 56th** [comment]
@lipnikov @dasvyat I forked, built, and moved ASC project to the newest version of Amanzi. Please see [here](https://github.com/56th/amanzi/tree/56th/ASC/src/operators#approximate-static-condensation-method). 

Everything compiles and works just fine (in terms of the matrix assembly, error computation etc). Paraview is able to visualize cell vals correctly for brick and tetra meshes, but **not** for polyhedral ones: it crashes with segmentation fault. 

I [attach](https://github.com/amanzi/amanzi/files/3413362/output_example.tar.gz) the output files + original .exo meshes for a brick, tetra, and polyhedral mesh. I output results [here](https://github.com/56th/amanzi/blob/edcd9085b76fde31aaa6e02bb2883550649a9919/src/operators/test/operator_diffusion_asc.cc#L221).

**Comment by lipnikov** [comment]
I need more details (error message, gdb output, etc). Paraview 5.6.0 on OSX 10.12.6 shows the polytopal mesh with 180 cells and solution on it.

**Comment by lipnikov** [comment]
Let us start with something which works. My working test is based on hacking the existing test:
[operator_remap.cc.gz](https://github.com/amanzi/amanzi/files/3413838/operator_remap.cc.gz)

**Comment by 56th** [comment]
@lipnikov I updated to Paraview 5.7.0 and it works just perfectly. :)
I was using 5.4.1 (Ubuntu). I think it is not worth your time to investigate the issue.

![poly](https://user-images.githubusercontent.com/8272247/61683184-30051c00-acda-11e9-89a3-1f081c591cb7.png)
