### ISSUE TITLE
PETSc repo moved to gitlab.com/petsc/petsc -- TPL Superbuild cannot find tarball

### ISSUE THREAD

**Issue by smolins** [amanzi/amanzi#326]
PETSc is on the move again. Now they are on gitlab.com/petsc/petsc which means that this in TPLVersions.cmake does not work any more

#
# TPL: PETSc
#
set(PETSc_VERSION_MAJOR  3)
set(PETSc_VERSION_MINOR  8)
set(PETSc_VERSION_PATCH  2)
set(PETSc_VERSION  ${PETSc_VERSION_MAJOR}.${PETSc_VERSION_MINOR}.${PETSc_VERSION_PATCH})
set(PETSc_ARCHIVE_VERSION ${PETSc_VERSION_MAJOR}.${PETSc_VERSION_MINOR}.${PETSc_VERSION_PATCH})
set(PETSc_URL_STRING     "https://bitbucket.org/petsc/petsc/get")
set(PETSc_ARCHIVE_FILE   v${PETSc_VERSION}.tar.gz)
set(PETSc_SAVEAS_FILE    petsc-${PETSc_ARCHIVE_VERSION}.tar.gz)
set(PETSc_MD5_SUM        ce207f60800e19cfb55a2d7a879ca42c)

**Comment by lipnikov** [comment]
Tests passed on konstantin/trilinos branch
