### ISSUE TITLE
Add support in bootstrap.sh for build stages to address Travis CI limits

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#334]
To be consistent across the builds / deployments we are planning to support, we use the bootstrap.sh.   With Travis CI the limit of 50 minutes is tight for just the build, particularly now that we push that build to dockerhub so we can run tests on it in a later stage of the CI.

To work around this problem we are adding support to bootstrap.sh to build in two stages.  This should make the travis script a little easier as well.

**Comment by lipnikov** [comment]
Do I need to add "RUN git checkout my-branch" to Docker stages on each my tracked branch?

**Comment by jd-moulton** [comment]
We need to handle branches explicitly to truly test PRs.  This would be another argument that needs to be passed into the docker build, but not sure how to get that information.   It's largely separate from this issue, so I'm creating a new issue for it (#342) and closing this one.
