### ISSUE TITLE
Interoperability of process kernels 

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#351]
The objective is to deliver two examples of interoperability: coupled flow + flow from Amanzi to ATS and  coupled flow + energy from ATS to Amanzi. Current master branch of ATS is almost compatible with the current state of Amanzi's master (only 1 compile error), which simplifies staging of work. Based on my conversation with Daniil, the strategy to achieve interoperability  could be broken into five stages. The ticker has been update to reflect recent discussions:

- [x] Resolve conflicts in header names. Troubling headers could be installed in a sub-directory and included as "amanzi/EOS_IdealGas.h" Also, we rename namespace EOS in Amanzi  to AmanziEOS  

- [ ]  Resolve initialization conflicts for evaluators. Amanzi initializes state fields and field evaluators followed by a PK initialization. ATS swaps initialization of the PK and field evaluators. Looks like initialization of evaluators should be a two-stage process: before and after PK initialization. 

- [x] Remove the second state from ATS in favor of field copies using tags.

- [x] Cross-linking of libraries. Some minor changes to build script may be needed.

- [ ] Upgrade Amanzi's converter. Note that parsing of a new multi-physics process_kernel list is already there.

**Comment by ecoon** [comment]
Can we chat a bit about this at some point?  I think Konstantin has done a nice job of laying out what would need to be done at this point.  And I've certainly been pushing for this for a long time.  But I'm a bit nervous that some of these tasks would be work that will be immediately overwritten.

Specifically, removing the second state from ATS is something that absolutely needs to be done, but I would prefer it to get done in the process of adapting ATS to use Tpetra and new state.  A lot of lines of code would need to get touched to do this, and it is the same lines of code that will need to be touched to use Tpetra Amanzi, but the touching is slightly different.

This is not true of all of the work.  Making decisions about namespacing, packing of physics, etc would be useful for both efforts, for instance.  Standardizing build scripts/cmake files across libraries would be fantastic (I've done some of this in the tpetra branch already).

I wonder if it would make sense to have some big picture discussion about Amanzi and ATS development priorities, and seeing what of this work we can move forward without doing work that will not be used.

**Comment by lipnikov** [comment]
I agree, since it touches many aspects, we need  a plan.  Telecon next week would be nice, since I see only part of the global picture. Would it be possible to adjust the 5-point plan to include high-level info regarding state work and tpetra work? For example, will Tpetra upgrade cover the whole code base?

**Comment by lipnikov** [comment]
see de6b46a

**Comment by lipnikov** [comment]
The first interoperability test was added to Amanzi.
