### ISSUE TITLE
TPLs configure with new MSTK and static libs

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#359]
On current master, with:

- MSTK 3.1.0 (TPL)
- HDF5 1.10.5 (TPL)
- cmake 3.12.4 (my system)

Using bootstrap and --disable-shared, configuring MSTK fails because it is unable to locate a suitable HDF5 because it calls FindHDF5 without specifying DF5_USE_STATIC_LIBRARIES=True.  At least in my cmake, FindHDF5 defaults to expecting shared libraries, so it goes looking in $AMANZI_TPLS_INSTALL_DIR for hdf5 libraries, but only finds static ones (since we told SuperBuild to build static ones), and then errors out.

Do you have this issue?  Do we need to update our required cmake version?  Would updating cmake even help?

Note, this is likely an MSTK bug or Cmake version issue because we tell MSTK to build static, so one might expect it to look for static HDF5.

**Comment by jd-moulton** [comment]
I do not have this problem, but will try to reproduce it.  Can you add a little more info, which compiler, and mpi.  Any other system info (linux, mac). Any log of standard out would be great.

**Comment by lipnikov** [comment]
Workaround: add this to Build_MSTK.cmake: 
  -DHDF5_HL_LIBRARIES:LIST=${HDF5_LIBRARIES}

**Comment by ecoon** [comment]
That makes sense to me Konstantin -- is there a reason MSTK is using FindHDF5 at all?  If we just built (or found) HDF5 ourselves, shouldn't we just tell MSTK to use these ones?  More generally, I would think that we shouldn't be 'finding or building" things in SuperBuild, then immediately finding them again in another package when we can specifically tell that package, "hey, use this one I just built..."

It is mac, OpenMPI 3.1.3, building with clang-1000.10.44.4, but I don't think these should matter -- just the cmake and MSTK versions.  Maybe you have a different/newer cmake?  I'll attach the FindHDF5.cmake that I have, as I suspect you could reproduce the issue just by using that instead?  

I don't have the logs because I promptly rebuilt with --enable-shared to make sure that, if I built HDF5 shared, MSTK would find that HDF5 as expected (and it did).  I can re-compile TPLs again with --disable-shared and get them again, but it was not a useful error message, because first it tried to match the HDF5 we built, failed to match that, then tried to use a system HDF5 with MSTK (despite setting HDF5_NO_SYSTEM_PATHS, because that doesn't seem to be a variable that is used in FindHDF5 in this version of cmake?), then failed with an error message saying that while it found HDF5, the version it found wasn't parallel (referring to the system HDF5, which isn't parallel).  I had to do some message() additions to FindHDF5.cmake to track where it was going wrong (I've included those additions in the attached file.)



[FindHDF5.cmake.txt](https://github.com/amanzi/amanzi/files/3796261/FindHDF5.cmake.txt)

**Comment by lipnikov** [comment]
After building HDF5, we do not set up all parameters generated by FindHDF5. I do not see an issue in calling FindHDF5 in multiple packages.

I reproduced the problem on Ubuntu with gcc 9.1.0 and verified the workaround suggested above.

**Comment by ecoon** [comment]
Ok, I see the difference, we are supplying libraries already for HDF5, but not HDF5_HL.  Will commit this fix in a minute.

**Comment by raovgarimella** [comment]
BTW, Julian has made a spackage for MSTK.


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by lipnikov** [comment]
Rao, what is the URL?

**Comment by raovgarimella** [comment]
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mstk/package.py


General documentation for Spack


https://spack.io/


--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________
