### ISSUE TITLE
Amanzi_TPL_HDF5_LIBRARIES 

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#361]
When Amanzi is installed, it exports a bunch of Cmake variables to config files for use by other codes (ATS).  This allows ATS to pick up exactly as if it had been configured in a single cmake run as with Amanzi.

The HDF5 version of this is exporting the unprocessed version of its library name, e.g.:

`$AMANZI_INSTALL_DIR/lib/AmanziConfigTPL.cmake` 

reads:

`set(Amanzi_TPL_HDF5_LIBRARIES hdf5::hdf5_hl-shared;hdf5::hdf5-shared;/Users/uec/codes/ats/amanzi-tpls/install-dev/lib/libz.dylib;m;dl)`

I am unsure whether:

1. That line should have the fully resolved path to HDF5 (in the same way that libz.dylib is specified) OR
2. ATS needs to call find_package(HDF5) or something similar to get the right names.

I would prefer the former -- my eventual goal is to make ATS a sub-repo of Amanzi that configures and builds directly within the Amanzi source, which would eliminate this issue completely, but we're not there yet...

**Comment by ecoon** [comment]
Example from a previous working version:

`set(Amanzi_TPL_HDF5_LIBRARIES /Users/uec/codes/ats/amanzi-tpls/install-0.88/lib/libhdf5_hl_debug.dylib;/Users/uec/codes/ats/amanzi-tpls/install-0.88/lib/libhdf5_debug.dylib;/Users/uec/codes/ats/amanzi-tpls/install-0.88/lib/libz.dylib;m;dl)`

**Comment by lipnikov** [comment]
If you restrict CMake search scope, then find_package() will work reliably. 

I think Amanzi is not ready to use CMake targets extensively, since TPLs do not support it.

**Comment by ecoon** [comment]
I'm going to close this for now -- I'm prepping changes in ATS to move ATS's build into Amanzi as a submodule (see https://github.com/amanzi/ats/pull/20 ) which will no longer make this an issue.

**Comment by ecoon** [comment]
We are trying to use the AmanziTargets.cmake files for linking with ELM now, and this is still a thing.

**Comment by ecoon** [comment]
Ok, actually calling find_package(HDF5) seems to fix the problem and get the right targets (hdf5_hl-shared) to work.
