### ISSUE TITLE
CI tests broken by new submodule update hook

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#384]
https://travis-ci.org/amanzi/amanzi/jobs/637056135?utm_medium=notification&utm_source=github_status

**Comment by ecoon** [comment]
Hmm, I thought I commented on this but it isn't showing up.

@jd-moulton Is this a new change with you trying to get submodules to update on push?  Or is this the call within bootstrap that is failing?

**Comment by jd-moulton** [comment]
This was resolve, and we have since switched to GitHub Actions.
