### ISSUE TITLE
Alquimia not failing through Amanzi

### ISSUE THREAD

**Issue by eibarker** [amanzi/amanzi#40]
Jobs launched through Akuna use Agni to manage the runs on NERSC.  To determine if a job is "done" and report success or failure, Agni looks for keywords in the stdout.  Specifically "Amanzi::SIMULATION_FAILED".   If a run fails inside of Alquimia, the exception doesn't make it back up to Amanzi's messaging.  I get the following without a SUCESSFUL or FAILED message:

CycleDriver      |  Reseting CD: TP 0 -> TP 1.
PFloTran_Alquimia_Setup() : 
  Reading : amanzi_0/amanzi.in
 WARNING: Card (NONISOTHERMAL) not found in input file.
 Aqueous primary species (Tc-99) not found in database.

 ERROR: Species not found in database.
 Stopping!

We need the termination to still report the expected text so Agni can kill the job.

**Comment by smolins** [comment]
Looks like pflotran is terminating the simulation due to an error in the input. Alquimia cannot communicate the error to Amanzi.

**Comment by lipnikov** [comment]
We can agree on the common terminal message, like SIMULATION_FAILED in Amanzi

**Comment by lipnikov** [comment]
There is no good portable solution to capture Fortran's stop signal, see this article: https://stackoverflow.com/questions/19596375/intercepting-fortran-stop-from-c

Perhaps, Agni should process a longer list of possible error messages.
