### ISSUE TITLE
Meaning of whitelist parameter

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#404]
Current design of the whitelist parameter is that all fields on this i/o list will be unblocked if they were blocked by other means. Suggestion is to block all fields that are not on the whitelist.

**Comment by zexuanxu** [comment]
This is exactly what I mean and want, also consistent with the amanzi input instruction "whitelist" [Array(string)] list of fields that should be written to the visualization file." The "whitelist" should block all fields that are not on the whitelist, in my understanding.

**Comment by lipnikov** [comment]
Documentation also says "First, we remove all fields matching the patterns specified by blacklist. Second, we add all fields matching the patterns specified by whitelist."  
It implies that you can block all fields using "blacklist" and them allow selected fields using "whitelist". Two parameters gives more flexibility.

**Comment by zexuanxu** [comment]
Oh, I understand this instruction now. I guess there is some confusion. And I still think the "whitelist" should block all fields that are not on the whitelist.

**Comment by lipnikov** [comment]
Amanzi team agrees that the implemented algorithm follows one of the established practices in computer science; although, it may look counter-intuitive at first glance.
