### ISSUE TITLE
Broken calculation of tag minor

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#413]
-- >>>>>>>> AmanziVersion.cmake
-- Found Git: /usr/bin/git (found version "2.20.1 (Apple Git-117)")
-- >>>> JDM: AMANZI_GIT_BRANCH = master
CMake Error at tools/cmake/AmanziVersion.cmake:120 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:45 (include)

**Comment by jd-moulton** [comment]
In commit  90b4b634d3, I added "?" after second digit in regex for the patch number.  
```
STRING(REGEX MATCH "\\.[0-9][0-9]?[\\.,-]" AMANZI_GIT_LATEST_TAG_MINOR ${AMANZI_GIT_LATEST_TAG_VER})
```
This makes second digit optional (so matching 0.89 and 1.1 work).
