### ISSUE TITLE
Input Spec/Schema is missing some region types

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#415]
The Developer (Native) spec defines some regions which do not appear in the User (Akuna) spec, and hence, are also missing from the schema.  As a start it seems like we should considering adding

 * [x]  line segment

as this is used for non-grid-aligned wells (sources). 

So it seems there are four steps

  * [x] update input spec
  * [x] update translator
  * [x] update schema
  * [x] add verification test or benchmark that uses the line segement

**Comment by lipnikov** [comment]
David, can you update the schema? I want to see on your patch how it works.
