### ISSUE TITLE
Input Spec/Multiple point definitions

### ISSUE THREAD

**Issue by EllenAPorter** [amanzi/amanzi#418]
**typedef_point** contains an attribute "coordinate" and is used for the region type point as a typedef_labeled_point (typedef_point with additional attribute "name"): 

`<point name="abc" coordinate="(x, y, z)"/>`

Points are also defined as elements under polygons as direct coordinates:

  <xs:complexType name="typedef_polygonal_surface">
    <xs:sequence>
      <xs:element name="point" type="typedef_coordinate" minOccurs="0" maxOccurs="unbounded" /> ...

`<point>(x, y, z)</point>`

Validating a file with a polygon currently gives schema validation error.  Recommending we change the polygon point type to typedef_point for consistency:

`<point coordinate="(x, y, z)"/>`

**Comment by lipnikov** [comment]
I think we dropped curly brackets some time ago "(x, y)" -> "x, y"

**Comment by lipnikov** [comment]
I was not able to reproduce this schema validation failure. I added polygonal_surface region to this test src/common/interface_platform/test/converter_u_test4.xml for additional testing.

**Comment by EllenAPorter** [comment]
Schema allows ('s in the coordinate definition - Akuna will read a file with or without them.  We will not write them out.  Perhaps another issue should be opened to remove them from the coordinate definition?

Test file works okay, closing this issue.
