### ISSUE TITLE
bootstrap + clm without ats_physics

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#419]
Currently there is not default value for clm set in bootstrap (on the master branch).  This causes problems with bash on OSX at least, maybe elsewhere. 

Also, we should be able to build the pf-clm library as part of our TPLs collection, independently of what physics we build later when we build Amanzi or ATS.   However, building the clm library currently requires that ats_physics is enabled, which requires amanzi_physics is disabled.

**Comment by jd-moulton** [comment]
Commented out for now, probably should separate the options between building the TPL and building the capability in ATS.  Will look at working with @ecoon and fixing this on the branch first.

**Comment by ecoon** [comment]
I don’t especially have a need to separate the options between tpls and ATS — we don’t do that for e.g. Hypre or geochemistry or any other package and Amanzi, do we?  Agree that CLM shouldn’t require ATS.

**Comment by ecoon** [comment]
I think this can be closed?  I don't particularly want to separate out the logic of building CLM in TPLs from that of building CLM components in ATS -- we use one flag (e.g. ENABLE_HYPRE) to do both in multiple cases elsewhere so having a single ENABLE_CLM makes sense to me from a consistency pattern.

And I think things work now to build CLM independently of the physics package.
