### ISSUE TITLE
Deployment of Amanzi and ATS in Docker Containers

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#422]
Building on the Docker containers we use Travis CI, create Docker Files and simple scripts to deploy builds as Docker containers on Dockerhub.

**Comment by banesullivan** [comment]
is this work in progress? i.e. are there docker files somewhere but no deployed containers?

**Comment by banesullivan** [comment]
In case anyone else is searching for the container on Docker Hub: https://hub.docker.com/r/metsi/amanzi

**Comment by jd-moulton** [comment]
It's a work in progress.  I'm pushing a build from yesterday up so that "latest" will be pretty recent. We haven't decided how often to really deploy a "latest" build.  

Similarly, release builds can be done by hand.  But ideally we'll get this setup so official releases as well as latest HEAD on the stable branches are available.

**Comment by jd-moulton** [comment]
It's there now, and is fairly current:

```
pn1806419:~ moulton$ docker run metsi/amanzi:latest /home/amanzi_user/install/bin/amanzi --print_version
Amanzi Version  1.1-dev_c4c0aecca
GIT branch      master
GIT global hash c4c0aecca
ERROR: No xml input file was specified. Use the command line option --xml_file to specify one.
Amanzi::SIMULATION_DID_NOT_RUN
```
Looks like I should add the install path to the amanzi_user's $PATH.

**Comment by jd-moulton** [comment]
Still need to do one for ATS.

**Comment by jd-moulton** [comment]
Fixed the path in the container:

```
docker run metsi/amanzi:latest amanzi --print_version
```

works and gives:

```
Amanzi Version  1.1-dev_bd4eee513
GIT branch      master
GIT global hash bd4eee513
ERROR: No xml input file was specified. Use the command line option --xml_file to specify one.
Amanzi::SIMULATION_DID_NOT_RUN
```

**Comment by banesullivan** [comment]
I've managed to make a Dockerfile based on the `amanzi_tpls` image that uses the build instructions in [INSTSALL_ATS.md](https://github.com/amanzi/amanzi/blob/master/INSTALL_ATS.md). 

@jd-moulton, would you be able to take a look at the Dockerfile at the bottom to double-check what I did? I ran into a build issue at:

```bash
...
[ 61%] Performing configure step for 'trilinos'
-- trilinos configure command succeeded.  See also /home/amanzi_user/amanzi_tpls-build-master-Release/trilinos/trilinos-timestamps/trilinos-configure-*.log
[ 61%] Performing build step for 'trilinos'
CMake Error at /home/amanzi_user/amanzi_tpls-build-master-Release/trilinos/trilinos-timestamps/trilinos-build-Release.cmake:16 (message):
  Command failed: 2

   'make'

  See also

    /home/amanzi_user/amanzi_tpls-build-master-Release/trilinos/trilinos-timestamps/trilinos-build-*.log


make[2]: *** [trilinos/trilinos-timestamps/trilinos-build] Error 1
CMakeFiles/trilinos.dir/build.make:117: recipe for target 'trilinos/trilinos-timestamps/trilinos-build' failed
CMakeFiles/Makefile2:1166: recipe for target 'CMakeFiles/trilinos.dir/all' failed
make[1]: *** [CMakeFiles/trilinos.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Amanzi Bootstrap ERROR: Failed to build TPLs
The command '/bin/sh -c ${AMANZI_SRC_DIR}/bootstrap.sh    ${dbg_option}    --with-mpi=${OPENMPI_DIR}    --enable-shared    --enable-clm    --disable-structured  --enable-unstructured    --disable-stk_mesh --enable-mstk_mesh    --disable-build_user_guide    --enable-hypre    --enable-silo    --disable-petsc    --disable-amanzi_physics    --enable-ats_physics    --disable-ats_dev    --disable-geochemistry    --amanzi-install-prefix=${AMANZI_DIR}    --amanzi-build-dir=${AMANZI_BUILD_DIR}    --tpl-install-prefix=${AMANZI_TPLS_DIR}    --tpl-build-dir=${AMANZI_TPLS_BUILD_DIR}    --tpl-download-dir=${ATS_BASE}/amanzi-tpls/Downloads    --tools-download-dir=${ATS_BASE}/amanzi-tpls/Downloads    --tools-build-dir=${ATS_BASE}/build    --tools-install-prefix=${ATS_BASE}/install    --with-cmake=`which cmake`    --with-ctest=`which ctest`    --branch_ats=${ATS_VERSION}    --parallel=6' returned a non-zero code: 30
```

Note some quirks:

- the TPLS image has no `latest` tag? so I used the `0.97.3` version
- I ran into issues using those HTTPS proxies, so I disabled them.

Todo:

- [ ] I need to install Python 3.x in the container and adjust the Python path accodringly.

-----

Dockerfile here:

<details>

```bash
ARG amanzi_tpls_ver=0.97.3
FROM metsi/amanzi-tpls:${amanzi_tpls_ver}
LABEL Description="Amanzi: Build and install Amanzi in a Docker image."

# Switch to amanzi_user
USER amanzi_user

RUN echo "${AMANZI_PREFIX}"
RUN echo "${AMANZI_TPLS_DIR}"

# Check build deps
RUN which cmake
RUN which mpicc
RUN dpkg -l | grep libblas

# Arguments
# ARG amanzi_branch=master
ARG ATS_BASE=/home/amanzi_user
ARG ATS_BUILD_TYPE=Release
ARG ATS_VERSION=master
ARG OPENMPI_DIR=/usr

ARG AMANZI_TPLS_BUILD_DIR=${ATS_BASE}/amanzi_tpls-build-${ATS_VERSION}-${ATS_BUILD_TYPE}
ARG AMANZI_TPLS_DIR=${ATS_BASE}/amanzi_tpls-install-${ATS_VERSION}-${ATS_BUILD_TYPE}

ARG AMANZI_SRC_DIR=${ATS_BASE}/amanzi
ARG AMANZI_BUILD_DIR=${ATS_BASE}/amanzi-build-${ATS_VERSION}-${ATS_BUILD_TYPE}
ARG AMANZI_DIR=${ATS_BASE}/amanzi-install-${ATS_VERSION}-${ATS_BUILD_TYPE}


ARG ATS_SRC_DIR=${AMANZI_SRC_DIR}/src/physics/ats
ARG ATS_DIR=${AMANZI_DIR}

ARG PATH=${ATS_DIR}/bin:${PATH}
ARG PATH=${AMANZI_TPLS_DIR}/bin:${PATH}
ARG PYTHONPATH=${ATS_SRC_DIR}/tools/utils:${PYTHONPATH}
ARG PYTHONPATH=${AMANZI_TPLS_DIR}/SEACAS/lib:${PYTHONPATH}

ARG dbg_option=--opt

# Change the Working Directory and update amanzi
WORKDIR /home/amanzi_user/amanzi

# ENV https_proxy=proxyout.lanl.gov:8080 \
#     http_proxy=proxyout.lanl.gov:8080

# Make sure we have updated branch information
RUN echo "Amanzi branch = $ATS_VERSION"
RUN git pull
RUN git branch --list
# Checkout the branch and update it
RUN git checkout $ATS_VERSION
RUN git pull


# One last check of variables
RUN echo "Running Amanzi Boostrap with:"
RUN echo "  AMANZI_SRC_DIR: ${AMANZI_SRC_DIR}"
RUN echo "  AMANZI_BUILD_DIR: ${AMANZI_BUILD_DIR}"
RUN echo "  AMANZI_INSTALL_DIR: ${AMANZI_DIR}"
RUN echo "  AMANZI_TPLS_BUILD_DIR: ${AMANZI_TPLS_BUILD_DIR}"
RUN echo "  AMANZI_TPLS_DIR: ${AMANZI_TPLS_DIR}"
RUN echo " with build type: ${ATS_BUILD_TYPE}"
RUN echo ""


# DO THE BUILD!!!!!!!!!
RUN ${AMANZI_SRC_DIR}/bootstrap.sh \
   ${dbg_option} \
   --with-mpi=${OPENMPI_DIR} \
   --enable-shared \
   --enable-clm \
   --disable-structured  --enable-unstructured \
   --disable-stk_mesh --enable-mstk_mesh \
   --disable-build_user_guide \
   --enable-hypre \
   --enable-silo \
   --disable-petsc \
   --disable-amanzi_physics \
   --enable-ats_physics \
   --disable-ats_dev \
   --disable-geochemistry \
   --amanzi-install-prefix=${AMANZI_DIR} \
   --amanzi-build-dir=${AMANZI_BUILD_DIR} \
   --tpl-install-prefix=${AMANZI_TPLS_DIR} \
   --tpl-build-dir=${AMANZI_TPLS_BUILD_DIR} \
   --tpl-download-dir=${ATS_BASE}/amanzi-tpls/Downloads \
   --tools-download-dir=${ATS_BASE}/amanzi-tpls/Downloads \
   --tools-build-dir=${ATS_BASE}/build \
   --tools-install-prefix=${ATS_BASE}/install \
   --with-cmake=`which cmake` \
   --with-ctest=`which ctest` \
   --branch_ats=${ATS_VERSION} \
   --parallel=6


# Unset proxy
# ENV https_proxy= \
#     http_proxy=
```

</details>

**Comment by jd-moulton** [comment]
@banesullivan Apologies the instructions to build ATS are outdated.  I didn't realize this, but we now have ATS as submodule and it is built with bootstrap.sh.  So you just need to copy the Dockerfile-Amanzi and change a couple of options.  I can't get to it until later today.   But it would be good for you to look at the amanzi test_suite first anyway.  The tests are described and results are shown in the [Amanzi User Guide](https://amanzi.github.io/amanzi/UserGuide). You should be able to run these flow and transport examples with the Amanzi docker image.

**Comment by jd-moulton** [comment]
@banesullivan I created an initial Dockerfile for ATS and pushed the image up to docker hub. 

```
docker run --rm metsi/ats:latest ats
```

Does run, although doesn't exit cleanly.  I'll check into this part.  So you should be able to use it the same way the amanzi container works.  There isn't a --print_version option yet for ATS, but you could try to run something from [ats-demos](https://github.com/amanzi/ats-demos) repo using the same mountpoint for local disk access as in the Amanzi container.

**Comment by banesullivan** [comment]
Awesome, thanks @jd-moulton!

**Comment by banesullivan** [comment]
@jd-moulton, I've been able to run [the Amanzi turorials](https://amanzi.github.io/amanzi/UserGuide/tutorial/index.html) in the `metsi/amanzi` container as well as spinup the `ats` image. At the moment, I am trying to figure out what's going on with the `ats-demos`. Do I need to perform some linking between the build of ATS and Python? I see the  `tools/py_lib/` directory with some Python modules that I could import, but I do not see the `column_data` and `parse_xmf` modules (these are amanzi/ats specific and not TPLs, correct?).

**Comment by banesullivan** [comment]
is the ATS source not included in the `metsi/ats` image? I cannot find the ATS tools like https://github.com/amanzi/ats/blob/master/tools/utils/column_data.py and https://github.com/amanzi/ats/blob/master/tools/testing/test_manager.py

which are needed for the ats-demos:

https://github.com/amanzi/ats-demos/blob/73e685edf1f66c194278d46709acb57a235d9db8/run_demos.py#L20-L21

**Comment by jd-moulton** [comment]
ATS is a submodule, look under src/physics/ats.  The repo should be there and so that's where you should find the "tools" subdirectory.

**Comment by banesullivan** [comment]
Aha! Thansk!

**Comment by ecoon** [comment]
Yeah, it would be good to define ATS_SRC_DIR in these.  Also, because these use Joe's script, they do not build geochemistry, so some of the demos cannot run.  This script needs to be cleaned up and generalized (or better yet, removed completely in favor of a non-one-size-fits-all script that allows users to call bootstrap themselves), but that is a different issue.

**Comment by banesullivan** [comment]
I am having trouble building the `ats` docker image from `Docker/Dockerfile-ATS` using the [`metsi/amanzi-tpls:0.97.6-openmpi`](https://hub.docker.com/layers/metsi/amanzi-tpls/0.97.6-openmpi/images/sha256-bd67dc086ec66dedec0111498234bea934bdedf7f4892f6ab3742119869af52e?context=explore) base image. I recieved an error:

<details>

```

```

</details>

I also tried building the TPLs image locally and ran into an issue with that Dockerfile as well:

<details>

```
...
[ 58%] Performing configure step for 'trilinos'
-- trilinos configure command succeeded.  See also /home/amanzi_user/amanzi_builddir/tpls/trilinos/trilinos-timestamps/trilinos-configure-*.log
[ 58%] Performing build step for 'trilinos'
CMake Error at /home/amanzi_user/amanzi_builddir/tpls/trilinos/trilinos-timestamps/trilinos-build-Release.cmake:16 (message):
  Command failed: 2

   'make'

  See also

    /home/amanzi_user/amanzi_builddir/tpls/trilinos/trilinos-timestamps/trilinos-build-*.log


make[2]: *** [trilinos/trilinos-timestamps/trilinos-build] Error 1
CMakeFiles/trilinos.dir/build.make:117: recipe for target 'trilinos/trilinos-timestamps/trilinos-build' failed
make[1]: *** [CMakeFiles/trilinos.dir/all] Error 2
CMakeFiles/Makefile2:1578: recipe for target 'CMakeFiles/trilinos.dir/all' failed
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Amanzi Bootstrap ERROR: Failed to build TPLs
The command '/bin/sh -c ./bootstrap.sh --prefix=${AMANZI_PREFIX}   --parallel=4 --opt   --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/amanzi   --tpl-build-dir=/home/amanzi_user/amanzi_builddir/tpls   --tpl-download-dir=/home/amanzi_user/amanzi_builddir/tpls/Downloads   --disable-build_amanzi --disable-build_user_guide   --enable-shared --enable-structured --enable-silo   --enable-alquimia --enable-pflotran --enable-crunchtope   --enable-pf_clm   --with-mpi=/usr   && git checkout master   && rm -r /home/amanzi_user/amanzi_builddir' returned a non-zero code: 30
```

</details>


@jd-moulton, would it be possible to add `deploy-ats-docker.sh` to the Travis script to update the `metsi/ats` image on DockerHub as it doesn't currently have the MPI (which was fixed recently). Or could someone manually update the `metsi/ats` image on DockerHub? https://hub.docker.com/r/metsi/ats/tags 


------

Also, is there a reason why the following is included in all Dockerfiles? I have comment these out to build locally:

```

**Comment by banesullivan** [comment]
I am having trouble building the `ats` docker image from `Docker/Dockerfile-ATS` using the [`metsi/amanzi-tpls:0.97.6-openmpi`](https://hub.docker.com/layers/metsi/amanzi-tpls/0.97.6-openmpi/images/sha256-bd67dc086ec66dedec0111498234bea934bdedf7f4892f6ab3742119869af52e?context=explore) base image. I received an error:

<details>

```
[ 62%] Linking CXX shared library libats_flow_relations.so
[ 62%] Built target ats_flow_relations
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Amanzi Bootstrap ERROR: Failed to build Amanzi
The command '/bin/sh -c ./bootstrap.sh --prefix=${AMANZI_PREFIX}    --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/amanzi    --tpl-config-file=${AMANZI_TPLS_DIR}/share/cmake/amanzi-tpl-config.cmake    --parallel=4 --opt    --disable-structured    --disable-build_user_guide    --disable-geochemistry    --disable-amanzi_physics --enable-ats_physics    --with-mpi=/usr    --enable-shared    && cd /home/amanzi_user/amanzi_builddir/amanzi' returned a non-zero code: 50
```

</details>

I am currently attempting to build the TPLs image to retry building the ATS image... will have to report back on if that works.



@jd-moulton, would it be possible to add `deploy-ats-docker.sh` to the Travis script to update the `metsi/ats` image on DockerHub as it doesn't currently have the MPI (which was fixed recently). Or could someone manually update the `metsi/ats` image on DockerHub? https://hub.docker.com/r/metsi/ats/tags 


------

Also, is there a reason why the following is included in all Dockerfiles? I have comment these out to build locally:

```
ENV https_proxy=proxyout.lanl.gov:8080 \
    http_proxy=proxyout.lanl.gov:8080
```

**Comment by jd-moulton** [comment]
Working well enough for this release.  Feature requests should open a new issue.
