### ISSUE TITLE
Shadow variable

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#428]
Potential issue:

src/mesh/mesh_mstk//MeshColumn.hh:506:18: warning: non-static data member 'column_faces_' of 'MeshColumn'
      shadows member inherited from type 'Mesh' [-Wshadow-field]
  Entity_ID_List column_faces_;
                 ^
src/mesh/Mesh.hh:905:39: note: declared here
  mutable std::vector<Entity_ID_List> column_faces_;

**Comment by ecoon** [comment]
Is this new?  Haven’t seen a warning for this yet, and I have shadow warnings on.  Will fix it, thanks for pointing it out.

**Comment by lipnikov** [comment]
It was there for quite some time.
