### ISSUE TITLE
CCSE doesn't build with MPI version 4

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#436]
In 1996, the constructs MPI_LB and MPI_UB were deprecated, but these are still used by CCSE 1.3.4.  MPI version 3 formally removed them from the standard, though at least OpenMPI still implemented them.  My OpenMPI version 4.0.3 which is the default on my laptop now removed them completely.

I'd hate to limit the version of MPI because of an old library -- any thougths?

**Comment by lipnikov** [comment]
I am upgrading CCSE to BoxLib and then to AMRex. First PR is pending David’s approval. This may fix the issue. Meanwhile I edit CCSE manually for MPI 4.

**Comment by ecoon** [comment]
ok great, thanks.  I'm fixing the pull request now, but had to get bootstrap to build MPI for me to get an older one.

**Comment by lipnikov** [comment]
The CCSE logic is not clear regarding usage of MPI_UB/MPI_LB, so I did not patch it for MPI 4. I hope that the recent AMRex fixed it.

**Comment by jd-moulton** [comment]
@ecoon and @lipnikov can you check on this.  This seems to work with openmpi 4.x now, and I assume it's because Konstantin carried on with a few more updates.  If so we could close this ticket.

**Comment by jd-moulton** [comment]
No other feedback received, assuming it's working now.
