### ISSUE TITLE
oddities in PDE_DiffusionMFDwithGravity under various little_k concepts.

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#439]
I've been staring at the various upwind methods in MFD and MFDwithGravity as I migrate that code to Tpetra.

Is this branch of code reachable?
https://github.com/amanzi/amanzi/blob/master/src/operators/PDE_DiffusionMFDwithGravity.cc#L93

It seems to me that this definition of fv_flag:
https://github.com/amanzi/amanzi/blob/master/src/operators/PDE_DiffusionMFDwithGravity.cc#L67

should not allow line 93 to be reached.  

Finally, there are some subtle difference in how kr is set up between the three locations (PDE_DiffusionMFD::UpdateMatrices, PDE_DiffusionMFDwithGravity::AddGravityToRHS_ and PDE_DiffusionMFDwithGravity::UpdateFluxes) and I just want to make sure those subtle differences are correct and not bugs.  Most obviously, under DIVK_TWIN, the twin is not used in AddGravityToRHS_().  Presumably that is intentional.

Also, is there a reason there is no branch for the case OPERATOR_LITTLE_K_DIVK_TWIN here?:
https://github.com/amanzi/amanzi/blob/master/src/operators/PDE_DiffusionMFDwithGravity.cc#L208

**Comment by lipnikov** [comment]
With GRAVITY_FV active, the flag  is true and line 93 is reachable.

**Comment by lipnikov** [comment]
TWIN is an experimental and probably not complete. It make sense to move it to a test/MyPDE_DiffusionMFD.

**Comment by ecoon** [comment]
Great, thanks.
