### ISSUE TITLE
Write sorbed_concentration in amanzi observation file

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/amanzi#447]
I would like to have the capability in amanzi low-level spec input to write the sorbed_concentration into an observation file. From the code mpc/ObservableSolute.cc and mpc/ObservableFactory.cc, it seems only the total_concentration can be exported as "aqueous_conc”. 

It will be great if the developer can provide any examples as well for this.

Thanks
Zexuan

**Comment by lipnikov** [comment]
We do create and populate state field called "total_sorbed", so a new observation, say "sorbed_conc" is easy to implement. 

Regarding examples: Do you mean more examples in the Native Spec?

**Comment by zexuanxu** [comment]
Hi Konstantin, thanks! Well, I just mean an example of the syntax, say "sorbed_conc", so users know what keyword they should use.

**Comment by lipnikov** [comment]
I have not decided if the new observation fits better liquid phase or solid phase, so it is under liquid phase now.

**Comment by lipnikov** [comment]
I assume constant particle density for an observation region. Let me know if you need a more accurate estimate and will provide additional rock data in your input files.

**Comment by zexuanxu** [comment]
Thanks! That looks great - I will take a try and let you know if I have any questions.

**Comment by zexuanxu** [comment]
Hi Konstantin,

Could you help implement those changes in amanzi-0.87 (instead of master) as well, since it seems I'm not able to transit to master immediately because of the pflotran issue. I know simply copy/paste files in masters to amanzi-0.87 won't work, and I did try to implement those changes to amanzi-0.87 by my own, but obviously I don't know the code enough so I got some issue (e.g., all observation values are 0).

Thanks!

**Comment by lipnikov** [comment]
I wonder if crunchflow could be used for the same chemistry in Amanzi-1.0.

Since I do not have TPLs for 0.87, rebuilding them on a new hardware/software with 0.87 scripts may be a challenge. We fixed multiple issues since that time. But your problem (zero observations) may have a simpler solution. What are the observation sections in your high-level and native specs? Also, can you put .cc files modified for new observations in the same directory on NERSC.
