### ISSUE TITLE
Read time-series hdf5 file in amanzi high-level input file

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/amanzi#448]
Hi developers,

I would like to see that the time-series HDF5 file can be read by the amanzi high-level input file. For now, I believe high-level input file can only read multiple "piecewise" constant functions for inward_volumetric_flux but not from an external HDF5 file. Although the low-level (native) spec supports reading data from HDF5 file, but I personally would like to see this capability supported in the high-level spec file.

**Comment by lipnikov** [comment]
I pushed some changed. Example below should work in a few places for cell-centered fields. Can you provide a snapshot of a potential input spec that you would like to be supported?

```
  <porosity type="h5file" filename="porosity.h5" constant_in_time="true"/>
```

**Comment by lipnikov** [comment]
Boundary data. The major obstacle is how to handle face-centered data in a parallel run if the data are given only on the boundary. HDF5 may have required i/o capabilities, I do not know and need to read the HDF5 manual. 

Meanwhile I want to mention recent capability of Amanzi i/o. The piecewise constant data can be replaced by any piecewise mathematical function of t, x, y, and z. Moreover, if statement can be inserted inside the body of a math function, see GitHub project ExprTk for more details. Example is

```
        <liquid_component name="water">
          <inward_volumetric_flux value="1.1071e-10" function="constant" start="0.0" />
          <inward_volumetric_flux value="0.00254022e-3" function="constant" start="6.17266656e+10" />
          <inward_volumetric_flux function="general" formula="exp(t) * (x + y * sin(z))" start="6.1729344E10" />
          <inward_volumetric_flux value="1.48666E-9" function="constant" start="9.4672798E10" />
        </liquid_component>
```

**Comment by zexuanxu** [comment]
Hi Konstantin,

I think what I mean is something like the time-series recharge rate (not constant in time, but single value for each year or day, for example). I copied what I edited in the low-level spec for reading time-series boundary conditions. For now, I don't think I need to read spatial heterogeneous data.

              <ParameterList name="outward mass flux">

                <ParameterList name="function-tabular" type="ParameterList">
                  <Parameter name="file" type="string" value="./recharge_forcing.h5"/>
                  <Parameter name="x header" type="string" value="/year"/>
                  <Parameter name="y header" type="string" value="/recharge_rcp26"/>
                </ParameterList>
              </ParameterList>

**Comment by lipnikov** [comment]
Thanks for clarifying, it is a simpler task than I thought originally.

**Comment by lipnikov** [comment]
Please re-open the ticket if this upgrade will not work for you.
