### ISSUE TITLE
Test: chemistry_benchmarks_1d

### ISSUE THREAD

**Issue by ajkhattak** [amanzi/amanzi#459]
I pulled Amanzi and ATS master branches today and this test is failing for me (this test has never passed for me). Please see a snippet of the LastTest.log file below, the issue is the missing (or can't locate) calcite_data.h5 file. I have used amanzi/build_ATS_generic.sh for building. This is also related to the PR #446, where I see the missing "calcite_data.h5" is causing CI to fail. Any thoughts? 

114/127 Testing: chemistry_benchmarks_1d
114/127 Test: chemistry_benchmarks_1d
Command: "/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/build-1.0-master/Debug/src/pks/chemistry/chemistry_benchmark_1d"
Directory: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi/build-1.0-master/Debug/src/pks/chemistry
"chemistry_benchmarks_1d" start time: Jul 08 11:36 EDT
Output:
----------------------------------------------------------
sh: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi/build-1.0-master/Debug/src/common/standalone_simulation_coordinator/amanzi: No such file or directory
/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0-master/src/pks/chemistry/test/chemistry_benchmarks_1d.cc:110:1: error: Failure in AmanziUCalcite: Expected 0 but was 32512
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5Fint.c line 1498 in H5F_open(): unable to open file: time = Wed Jul  8 11:36:31 2020
, name = 'calcite_data.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'calcite_data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5G.c line 453 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/build-1.0-master/Debug/src/common/standalone_simulation_coordinator/amanzi --xml_file=/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0-master/test_suites/benchmarking/chemistry/calcite_1d/amanzi-u-1d-calcite.xml
Ca++ concentration L2 norm: 3.40282e+38
/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0-master/src/pks/chemistry/test/chemistry_benchmarks_1d.cc:123:1: error: Failure in AmanziUCalcite: conc_L2 < 0.025
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5G.c line 453 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
Ca++ volume fraction L2 norm: 3.40282e+38
/software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0-master/src/pks/chemistry/test/chemistry_benchmarks_1d.cc:129:1: error: Failure in AmanziUCalcite: VF_L2 < 0.0002
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/build-1.0-master/Debug/hdf5/hdf5-1.10.6-source/src/H5F.c line 671 in H5Fclose(): not a file ID
    major: File accessibilty
    minor: Inappropriate type
FAILURE: 1 out of 1 tests failed (3 failures).
Test time: 0.37 seconds.
<end of output>
Test time =   0.78 sec
----------------------------------------------------------
Test Failed.
"chemistry_benchmarks_1d" end time: Jul 08 11:36 EDT
"chemistry_benchmarks_1d" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by lipnikov** [comment]
".../common/standalone_simulation_coordinator/amanzi: No such file or directory"
Executable amanzi is missing, this explains the errors. The number of tests (127) is too small. Should be about 173. To test Amanzi, you should enable amanzi physics and disable ats physics in your shell script.

**Comment by ajkhattak** [comment]
yeah, I have disabled amanzi physics, so the question is can we turn ON both Amanzi and ATS physics together without any issue? Have never tried it before since ATS became a subrepo.

**Comment by jd-moulton** [comment]
Not currently (working on it). For now you need to have two separate builds, and verify all tests pass in both cases. Also for the ATS you'd want to verify their regression tests pass.
