### ISSUE TITLE
SuperLU moved?

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#461]
This link seems to be dead:

https://github.com/amanzi/amanzi/blob/master/config/SuperBuild/TPLVersions.cmake#L412

**Comment by ecoon** [comment]
We're using a github site for SuperLUDist though...

https://github.com/xiaoyeli/superlu_dist/archive

Probably should use the github for SuperLU, but there are no releases there that I can find...

**Comment by ecoon** [comment]
Maybe it is just that NERSC's websites are all down -- I'm not getting anything at portal.nersc.gov either.

I guess we can wait til Monday:

> Tomorrow, July 10, starting at 6:00 am Pacific time, NERSC will begin powering down must user systems in preparation for the power maintenance that will take place Saturday through Monday. Most user systems, including Cori, DTNs, and all storage systems, will remain powered off for the duration of the outage. Non-compute auxiliary services -- including Iris, Spin, the NERSC website, and databases, along with any others not requiring file system access -- will remain available on generator power.

**Comment by lipnikov** [comment]
https://github.com/xiaoyeli/superlu/releases/tag/v5.2.1

Move to GitHub may help with this:
https://github.com/xiaoyeli/superlu_dist/issues/48

**Comment by ecoon** [comment]
Oh good, I wasn’t seeing those tags/releases.  That makes it easier.

Hyper has moved too...

**Comment by ecoon** [comment]
> https://github.com/xiaoyeli/superlu/releases/tag/v5.2.1
> 
> Move to GitHub may help with this:
> [xiaoyeli/superlu_dist#48](https://github.com/xiaoyeli/superlu_dist/issues/48)


I guess I’ll check if there is a new release of SuperLU since that fix.  If not, do you want me to pick an arbitrary commit?

Is there currently a patch being applied?  It sounds like we’ve been just working around it.  I’ll leave you to make more substantial changes to that build if you’d like them.

**Comment by lipnikov** [comment]
I remember that’s TPLs build order was important. The second SuperLU modified has extended header. So it is fine to overwrite the first grader. But if reinstall only one SuperLU, expect trouble. She fixed it.

**Comment by lipnikov** [comment]
Funny auto correction...
David fixed Hypre on a branch a few days back but he is waiting for something
