### ISSUE TITLE
memory leak in Ifpack_Hypre

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#473]
Note this is an upstream bug, but it is a pretty big deal for our current usage of Ifpack_Hypre because it leaks every time we create such an object, and currently we create one every linear solve...

https://github.com/trilinos/Trilinos/issues/7807

Note that I need to recheck -- it looks like there is some deferred setup available in Ifpack_Hypre now, and we have a new Hypre, so it is possible that the issues with block colors (which is why we had to recreate the object every linear solve) have been fixed.

If not, I need to submit a bug report to Hypre to fix that issue...

**Comment by lipnikov** [comment]
We are 2 years behind in Hypre releases. Should we upgrade Hypre first or it is not related?

**Comment by ecoon** [comment]
Not related.  But probably should be upgraded anyway.  Though to be honest, I would guess that most of the changes have been based on OpenMP and CUDA work they've been doing.

**Comment by lipnikov** [comment]
I think that new parallel ILU solvers and new coarsening algorithms were mentioned in the ChangeLog.

**Comment by ecoon** [comment]
This is fixed both in a patch, and now in Trilinos upstream, so closing it.  We will need to update our Hypre for use in ExaSheds, so will make a new ticket for that.
