### ISSUE TITLE
bug in SuperBuild or Alquimia cmake

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#478]
For some reason, when building Alquimia through Amanzi's SuperBuild and CMake I always end up with the following in Alquimia's CMakeCache.txt:

```
PETSC_INCLUDES:STRING=/Users/uec/code/ats/amanzi-tpls/install-ecoon-memory_management/relwithdebinfo/openmpi-4.0.4_1-clang-default/petsc-3.11.3/./include;/Users/uec/code/ats/amanzi-tpls/install-ecoon-memory_management/relwithdebinfo/openmpi-4.0.4_1-clang-default/petsc-3.11.3/include
```

Effectively `$PETSC_DIR/$PETSC_ARCH/include` is there twice, but it ought to be one for that and one for `$PETSC_DIR/$PETSC_ARCH/include/petsc`.

Manually editing this lets the build go through.

At one point I think @jd-moulton  and I had figured out a fix, but I can't find it.  So at some point I'll try to figure out a fix again and send a pull request.  I forget whether the fix is in SuperBuild (e.g. are we passing the right info to Alquimia's cmake about the PETSc we just built for Alquimia?) or in Alquimia's cmake.  So for now will put the issue here but might need to move this upstream.

**Comment by lipnikov** [comment]
This is correct for CrunchFlow which uses "#include pets/finclude/xxx.h"

**Comment by ecoon** [comment]
Oh, that's a good point, that sounds like better practice to me.

**Comment by ecoon** [comment]
raised this here: https://github.com/LBL-EESA/alquimia-dev/issues/66

**Comment by lipnikov** [comment]
Also, alquimia cannot find PETSc on OSX with gcc-10 from macport. The reason is that linking in multipass function has to use mpicxx (instead of mpicc) due to linking with superlu_dist library.  Language binding could be changed from "C" to "CXX" in line 266 of FindPETSc to resolve this issue.

**Comment by jd-moulton** [comment]
No longer seem to have problems with this issue.  If it can be reproduced somewhere we can reopen.

**Comment by ecoon** [comment]
yes, this was fixed upstream
