### ISSUE TITLE
update SEACAS to newer version, download from SEACAS repo

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#479]
This is not critical.

New SEACAS versions have fixed problems associated with gcc 10 -- see https://github.com/gsjaardema/seacas/issues/187

Also, we could take this opportunity to get on a SEACAS release cycle -- releases are provided at https://github.com/gsjaardema/seacas/tags

Note, this doesn't fix all gcc-10 issues, and still requires FFLAGS to be set (for netcdf-fortran), but it is a step in the right direction.

**Comment by ecoon** [comment]
@jd-moulton  Is this done with all the new work on Trilinos and other TPLs?

**Comment by lipnikov** [comment]
SEACAS was upgraded to version 2022.02.16
