### ISSUE TITLE
Derive TreeOperator from a base class

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#483]
Operator is the derived class but TreeOperator is not:
class Operator : public Matrix<CompositeVector,CompositeVectorSpace>  {
class TreeOperator {

Confirmed with Ethan that this should be fixed.

**Comment by ecoon** [comment]
Didn't realize you were doing this.  I just pushed a small commit onto master that does this as well (and then merges with your changes).  No real difference, just make sure the inherited methods returned something, even for block diagonal PC.
