### ISSUE TITLE
hypre archive and MD5

### ISSUE THREAD

**Issue by smolins** [amanzi/amanzi#484]
- github.com/LLNL/hypre is not found to download hypre TPL
- github.com/hypre-space/hypre works for download but MD5 hash is different

-- verifying file...
       file='/home/smolins/amanzi-ats/amanzi-dev/build/tpls/Downloads/hypre-2.14.0.tar.gz'
-- MD5 hash of
    /home/smolins/amanzi-ats/amanzi-dev/build/tpls/Downloads/hypre-2.14.0.tar.gz
  does not match expected value
    expected: 'ecde5cc807ec45bfb647e9f28d2eaea1'
      actual: '270a6e4620622516655dd9903a36d314'

**Comment by ecoon** [comment]
Fixed a while ago
