### ISSUE TITLE
use chemistry PK factory without Alquimia

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#495]
One ought to be able to compile Amanzi with reactive transport using Amanzi chemistry without compiling Alquimia.

It appears that is not possible currently because the PK factory registration is not generated on the fly, but instead is generated a priori and commited into Amanzi codebase.  I believe all that is needed to get this to work is adding `#ifdef ENABLE_ALQUIMIA` protections here:

https://github.com/amanzi/amanzi/blob/master/src/pks/chemistry/pks_chemistry_registration.hh#L12

(and on the registration of alquimia chemistry a few lines later).

**Comment by ecoon** [comment]
@JulienLoiseau can you check that if you protect lines 12 & 18 in the above file, that you can build and run your failing test with AmanziPhysics on and Alquimia off?

**Comment by JulienLoiseau** [comment]
I might add: 
#ifdef ALQUIMIA_ENABLED

Like in: https://github.com/amanzi/amanzi/blob/f6c209fa7cbe9051802633ce372b4b088f72d91e/src/pks/chemistry/Chemistry_PK.hh#L25

Defined at: 
https://github.com/amanzi/amanzi/blob/f6c209fa7cbe9051802633ce372b4b088f72d91e/src/CMakeLists.txt#L21

**Comment by lipnikov** [comment]
If you need chemistry, you should probably enable Alquimia. Amanzi's chemistry is for toy problems. Or do you plan to invest in it?

**Comment by JulienLoiseau** [comment]
I dont need chemistry and alquimia is disabled but I get error due to this at compile time. (Working on the spack version, not using the bootstrap). 
By adding this flags it work for boths cases.

**Comment by ecoon** [comment]
While the user may not need or want chemistry, the unit test (mpc_reactive_transport I believe?) still is compiled, and runs/passes using Alquimia chemistry.  So the build fails.

Julien, can you submit a pull request adding the ifdefs off of master?  We've talked about this for longer than it takes to fix now :D
