### ISSUE TITLE
major Mesh refactor

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#499]
Konstantin's new changes to the Mesh infrastructure are bringing up some opportunities to refactor Mesh to make it a bit easier, more performant, and cleaner.

* With the exception of edges, we use the entirety of the cache in all runs.  Furthermore, in all cases, when we deform the mesh, we do so globally.  So there is little point to maintaining an elaborate logic around "recompute" and lazy caching.  Effectively I propose we move to a model where there is a single `UpdateCache()` call that is called both at setup and in any`Deform()` calls, etc.  Then simplify all cache methods to just return the thing instead of checking if recompute, if created, etc.

* `cell_map()` access is currently virtual.  So is `map()`.  So is `GID()`. This is bad because it means they can't be used in an inner loop.  Instead, each mesh implementation should create the maps at initialization, and the base class should have non-virtual accessors.

* Many of the methods which query topology pass in an array.  This means they must be copied -- instead, one could return those arrays by const reference (since they are cached as arrays already).  For instance, `void cell_get_faces(Entity_ID c, Entitity_ID_List& faces)` could become `const Entitity_ID_List& cell_get_faces(Entity_ID c)`.  

* Finally, the container used in the Cache may need to change -- for instance, we have a version of this in Tpetra branch that uses Kokkos::View<Entity_ID*> instead of std::vector<Entity_ID>.  Some flexibility here would help a lot.

**Comment by lipnikov** [comment]
I support simplifying the lazy caching logic. Also, with UpdateCache() we should be able to eliminate virtual *internal_() functions from MeshLight making is more "light". 

In dynamic cases, having two meshes may be useful. I suggest that major refectory will make a room for a mesh copy constructor.

**Comment by ecoon** [comment]
Ok, I've started in on this a bit.  First task is splitting this beast up a bit.  I don't believe that the following capability should be in Mesh:
- deform should be nonmember functions that act on a mesh, but shouldn't be a part of the main interface
- sets (with the exception of LabeledSets) should not be in the derived mesh class, but instead outside of it, which would allow that functionality to be used on all meshes
- columns should not be a part of Mesh, but outside of it
- conflating the cache and Mesh itself has caused a huge bloat of code
- The "recompute" option is not used in Amanzi, and the "ordered" option is trouble since it falls back to something expensive. 

I'm proposing the following:

1. Rename `Mesh --> MeshFramework`, removing cache, sets, deform, build_columns, leaving a bare set of geometric and topologic accessors.  Drastically simplify this interface, and standardize the function names to meet Amanzi naming convention standards.

On names, I'd like to use a slightly modified naming convention.  To me, there are three ways of capitalizing: "lower_case_with_underscores", "CamelCaseFirstCapitalized", and "camelCaseFirstLowercase" that are readable (trying to avoid "Upper_With_Underscores" wherever possible, but sometimes that is also useful).  Using those three ways of capitalizing, there are three types of names -- type or class names like "CompositeVector", local variables like "num_cells" or "cell_volume" and function names, which therefore should _not_ be "cell_volume()" or "num_cells()".  To me, function names should then be "getNumCells()", etc.  So they should be verbs (use get) and they should start with a lower case to distinguish from type names.  This is the convention that Trilinos uses in their newer packages.  I'd like to try it here, and if people hate it we can always sed back to the old style of "GetCellVolume()".  

Similarly, I can never remember whether it is "get_set_entities()" or "set_get_entities()".  Every other method in Mesh is "OBJ_get_OTHERS".  I'm ok with either "getSetEntities()" or "setGetEntities()", but it _must_ be consistent across Mesh, so all of them will be the same: either "cellGetFaces()" or "getCellFaces()", "entityGetPType()" or "getEntityPType()".  Preferences?

2. Update Mesh_MSTK, Mesh_MOAB, Mesh_Simple to implement the MeshFramework interface.  At first cut, this halved the size of Mesh_MSTK.cc.  There is a ton of repeated code based around C-style MSTK that can easily be generalized to use the public MeshFramework interface.  Things like `cell_get_coordinates()` is 40+ lines of C/MSTK code in Mesh_MSTK, but could be 4 or 5 lines of code in MeshFramework, implemented by using `cell_get_nodes()` and `node_get_coordinate()`.  Then it is only implemented in MeshFramework, and need not be implemented in all deriving classes.

3. Remove all "recompute" options.  This class will _always_ compute things, and _never_ cache them.  Nearly all implementations will be virtual.  It will be slow.  That's ok.

4. Remove all "ordered" options.  Always use the ordered version if it is available.  Again, this is ok if it is slow, since we're going to cache it.

5. Update MeshAudit to work on MeshFramework.

Then, add a few more helper classes and namespaces of non-member functions:
1. a MeshSets class which stores a map of all mesh sets and IDs. 
2. a MeshColumns class which implements column capability
3. a MeshCache object which stores the cache.  This will be entirely non-virtual, with all inline functions -- the goal is to make this as fast as possible so that all functions in this class compile away to nothing more than an array access.
4. a MeshAlgorithms namespace which implements the geometric work, things like computing cell centroids that were done in Mesh::compute_cell_geometry() methods but, when does as non-member functions, could be used by either MeshFramework or MeshCache.  And implements deform().
5. a MeshCacheUtils for non-member functions that populate MeshCache from MeshFramework.

Each of these will _only_ use the public MeshFramework interface, and so will work on any MeshFramework object (not just MSTK as it currently is).

Finally, implement a Mesh class which stores MeshCache, MeshSets, MeshColumns, etc as needed.  MeshLight could be a different class with less capability here if you wanted, or you could directly use MeshCache instead.  For things like MeshLogical and MeshSurfaceCell, the goal would be to have other ways of populating MeshCache that don't need to implement the full MeshFramework interface.

**Comment by ecoon** [comment]
@lipnikov @jd-moulton  some feedback would be useful here.

I'll push up a branch where I've started by creating a MeshFramework object that is a stripped down, CPU-only, virtual functions (no cache) version of Mesh.  This will give you a sense of what that class looks like.  I also think I can sed nearly all of the interface changes, so hopefully this doesn't cause too much hassle on physics code.

**Comment by lipnikov** [comment]
Are you proposing to enforce Trilinos convention (cellGetVolume) of the whole Amanzi code or just Mesh classes? cellGetFaces or getCellFaces is probably the matter of using it 100+ times, after that it doesn't matter.

getSetEntities() is better since the lower-case "set" is somewhat reserved.

I want to propose you the following: design the mesh framework such that the cache could be generated (in the future) for all needed upward and downward dependencies, as well as for node coordinates, so that MESH_Delete(mstk) could be called to release tons of internal MSTK memory. Comment1: upward connectivity should be reduced to pointers when
ParallelType=ALL is used. Comment2: most future mesh modification would be easier to implement on a cache than via MSTK machinery.

MeshLight is used to generate a one-face mesh in 3D cell, so potentially MeshCache could it make it obsolete.

**Comment by ecoon** [comment]
Just Mesh classes for now.  Likely I would use it also in tpetra branch, and we could update more of Amanzi as we like it or not.  I'm not quite crazy enough to want to try and do all of Amanzi yet.

Good point on getSetEntities(), which then suggests getCellFaces() for consistency.

Yes, I want to call MESH_Delete too.  And stop having to maintain the huge quantities of MSTK code without knowing anything about MSTK.

Agreed on Comment 1 -- I'm not sure we really should even need an option there, as I'm not sure we use it with OWNED.  Grep suggests we do in only a very few number of places, and I'm curious what those are and may go looking to see if they really need to be OWNED.  It would be nice to remove that option.   Good point on Comment 2.

**Comment by ecoon** [comment]
I'm doing some more formal profiling on a bigger problem, but I just did some quick and dirty "hot spot" profiling by starting a debugger and stopping it a bunch of times to see where we were.  3 out of 12 were in face_get_cells().  Statistically this is quite bad...

**Comment by raovgarimella** [comment]
So, scanning the code, my understanding is that you built the internal "cache" arrays at the start and jettison any callbacks to the specific mesh framework after that. Is that right? The idea of storing all the mesh data locally in a mesh class seems great because it gives opportunities for using said mesh class in Kokkos (possibly even CUDA) since you are not reaching back into MSTK or MOAB.

However, that begs this question: If you are using the a mesh framework like MSTK or MOAB merely as a way to populate the cache, why not do away with them entirely and just read straight from Exodus? Or is there still major functionality (perhaps partitioning?) you will depend on.

**Comment by lipnikov** [comment]
I think so. In general, we should have an option to keep the underlying framework for future development flexibility.

**Comment by ecoon** [comment]
Yeah, the goal of this is moving toward Kokkos -- Julien put in a cache that basically covers most of what we had previously also cached in Mesh, but using Views, and this will put master into a form that makes it easier to move to that model.

In terms of what we get from a mesh framework in that situation, partitioning is one, I/O is another, and there likely will eventually be worlds in which we need to infer some interpolants between meshes, and I know at least MOAB has hooks with some of the E3SM mesh remap world, and I know you have a lot of remapping capabilities.  Having a virtual interface as a fallback is a useful thing too -- one could imagine writing a mesh reader which implemented the interface and read, e.g. MPAS-O NetCDF meshes.

**Comment by ecoon** [comment]
First of a few PRs related to this will come in soon.  

PR1: The first step standardizes all CMakeLists/bootstrap arguments to mesh_mstk or MESH_MSTK, but not mstk_mesh or MSTK_Mesh etc.  This changes the option to ENABLE_MESH_MSTK not ENABLE_MSTK_Mesh etc.  

PR2: Update testing to share mesh files where possible and lean on MeshAudit in testing over the large stock of current testing code.  This will let me split out MeshFramework (and testing) from Mesh (and testing).

**Comment by ecoon** [comment]
This comment is for notes on testing...

mesh/
- mesh_geometry: subtest PLANAR (2D), SURFACE (disabled), SOLID (3D).  Structured tests, checking geometry of coordinates, MSTK only
- mesh_deform: deforms 2D and 3D, MSTK only
- mesh_columns: forms columnar mesh from 3D, MSTK only
- mesh_nanoflann: tests AmanziMesh::PointCloud, test of mesh algorithms but not Mesh itself

mesh_mstk/
- hex_*: exo files, 3D, test geometry and a bit of maps
- hex_*_sets.cc: Checks mesh sets on exo file
- hex_gen_*.cc: generated mesh, 3D, test geometry and a bit of maps, mostly just calls MeshAudit
- quad_gen_*.cc: 2D variant, basically just calls MeshAudit
- extract_surface: lots of tests on surface extraction, sets, etc
- extract_column: single test, not much to it.  Tests a volumetric extracted mesh (e.g a subset of a 3D mesh)
- deform_vols: tests MSTK deformation capability
- extnode_map: tests the exterior node map only

- column: tests the MeshColumn capability in mesh_mstk.  Is this MSTK code or can this be generic?
- surface_column: tests also the MeshSurfaceCell capability in mesh_mstk.  Same as above
- fracture: creates a "fracture" mesh from a set of faces in a 3D mesh.  Only checks that such a thing can be constructed, doesn't actually CHECK anything...

mesh_moab/
- hex_*: basically identical to MSTK version but with MOAB

mesh_simple/
- cell_numbering: checks a 1x1x1 hex mesh (generated, not exo)
- face_adj_cells: checks a 3x3x3 hex mesh (generated)
- maps: DOES NOT check maps, more checks on a 1x1x1 hex generated mesh
- sets: geometric only set checks on a 3x3x3 generated hex mesh


Strategy:
- replace all "checks a mesh" by a single Mesh-level test that does geometrically specific things if possible and calls MeshAudit always (most of the above don't).  Call it on all frameworks that support it.
- keep extraction tests at the level of Mesh as well -- in the new formulation extraction may possibly move to the cache, which would mean needing checks at the Mesh level not the framework level.
- all sets are done at the Mesh level (sets will be managed at the cache level in the revision)
- "special" mesh tests (e.g. mesh_mstk's column and surface cell objects) will be refactored (if possible) into a non-MSTK mesh later

So effectively there will be no framework-level tests -- all tests will act on a Mesh but only be called if the framework is appropriate.
