### ISSUE TITLE
potential bug? potential feature request?  in Release builds on NERSC

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#501]
On at least one example I've seen on a fairly recent build (August) of ATS, Release builds on NERSC do not print the error message on failure, but instead simply say:

```terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >```

This is entirely unhelpful.  On all builds on all machines, amanzi_throw() should print the error message.

**Comment by jd-moulton** [comment]
I've seen this on other systems as well.  I don't think it's unique to NERSC but we should try to track it down before the next release.

**Comment by ecoon** [comment]
I've tried to replicate this and failed.  I'll keep an eye out but closing for now, we can reopen if we can rediscover this issue.
