### ISSUE TITLE
Feature request: Output one or more user-specified components through "observations"

### ISSUE THREAD

**Issue by SaubhagyaGT** [amanzi/amanzi#504]
This is to highlight a limitation of current "observation" functionality and requesting user-control on component observed through "observations" parameter list in a multi-component transport problem. The existing ATS-Amanzi can output only first component in the "observations". It would be extremely helpful to be able to specify component(s) we wish to write in an output file.

**Comment by lipnikov** [comment]
This ticket should be probably moved to ATS part of the Amanzi-ATS.  I/O in Amanzi uses solution name, e.g.

<sorbed_conc solute="Ca">
    <functional>point</functional>
    <time_macros>EveryMonth</time_macros>
</sorbed_conc>

**Comment by ecoon** [comment]
It is implemented in Amanzi code though.  So will be closed in pull request on Amanzi.
