### ISSUE TITLE
region:point in stretched meshes is unreliable

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#515]
The current algorithm (in Mesh_MSTK) for identifying a "region: point" is a bit unreliable.  It effectively searches for the nearest node, then checks if the point is in any of the cells that use that node.  This fails for cases of stretched/elongated meshes, e.g. something like this...

```
   /^^^^^^^^|
/^^^^^^^^^^|
|   *      |
-----------
```
Effectively, the closest point may be the upper left corner, which doesn't touch the cell that contains *.

In this case, the region is found to be empty.

Something a bit more robust would be nice...

**Comment by ecoon** [comment]
I'm thinking it may make sense to do something like:

1. find the nearest cell centroid (check contained)
2. if not, find all neighboring cells (common face) and check contained
3. keep going til you find a cell

In the actual case that the point is NOT in the mesh, this could take a long time.  But since that is likely not intended by the user, I don't mind not being particularly efficient in that case -- it eventually will finish searching all cells.

The difficult part here is the parallelism.  This isn't a SIMD operation in the way that the current algorithm is -- if we do this in a SIMD way, every core that doesn't contain the point will do the worst-case scenario of checking all local cells.

I guess alternatively we could do something like check whether the point is in a box that contains the partition.  This would result in maybe one or two cores searching that will not match.  Maybe that is ok since this code runs once at the start of a run?

Any better ideas?

**Comment by ecoon** [comment]
Also, do we have an existing algorithm for determining if a point is in a given cell?  And if not, how permissive do we need to be?  Containment is quite easy in 2D, or in convex 3D, but even star convex 3D is hard.

**Comment by lipnikov** [comment]
A side comment: the fast search algorithm could be reused here. It will return all points in a sphere of a given radius. We could increase gradually this radius and stop when the max radius is reached. 

point_in_cell() is used for search for a point inside a cell. I think it assumes that the cell is star-shaped w.r.t to the point.

**Comment by ecoon** [comment]
Thanks, that's a big help.  Add this to my todo list...

**Comment by lipnikov** [comment]
A second step, a loop over all cells, has been added to find the cell containing a point.
