### ISSUE TITLE
Supporting meshes on multiple communicators

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#517]
I would like to make some progress toward a broader goal of supporting solves on problems that live on a sub communicator of MPI_COMM_WORLD.  The simplest form of this is our intermediate scale model in NGEE-Arctic, where we use both MPI_COMM_WORLD (for a 2D surface mesh of the global domain) and a bunch of columns, each of which live on MPI_COMM_SELF.

ExaSheds also has plans for working on subcatchments, where the full domain might exist on MPI_COMM_WORLD, but the the domain would be split into subdomains, each of which live on a sub communicator, and we would do full PK/nonlinear solves on subdomains.

This will require a few design decisions as we break the SIMD world.  Effectively more things will have to be careful about respecting the communicator on which they are working.

In the short term though, decisions need to be made about things like checkpointing.  In ASCEMIO, the hdf5 file and the communicator are bound together.  The file is opened with a given IOGroup, and if multiple groups try to open the same file (e.g. with multiple HDF5_MPI instances), the code currently fails silently and one of the two instances thinks it is writing but that data simply goes missing.  (I've discovered this the hard way in trying to write all MPI_COMM_SELF columns into a single checkpoint file at the same time -- there is no lock that stops you from doing this, so whoever has opened it first or most recently gets the write, and the others are just writing into nowhere, but the code happily keeps going.)  I believe that the only sane thing is going to be that there is at least one checkpoint file per communicator (rather than having to orchestrate blocking writes across MPI_COMM_WORLD to allow each communicator to take their turn writing to the same HDF5 file).

If we have multiple checkpoint files, it may make sense to simply have there be one checkpoint file per mesh, as opposed to one per communicator.  It's a bit tricky to index things by communicator, whereas meshes currently have names and it is easy to index things by strings.

Is anyone offended by having checkpoint files be organized as checkpoint directories?  For instance, we would have:

```
run/
  checkpoint0000/
    domain.h5
    surface.h5
  checkpoint0001/
    domain.h5
    surface.h5
```

At least by doing this, checkpoints could be tar'd up and kept together.  Restarts could still be referred to by only the checkpoint directory, e.g. "restart from checkpoint file"="checkpoint0001" as the filename would get filled in by the mesh name and is known to the restart.  

Finally, if I change things to do this by default, would Amanzi people get grumpy since they only deal with one domain most of the time?  Should I check that "if there is only one mesh, then just call it checkpoint00001.h5"?  Or would Amanzi users be ok with:

```
run/
  checkpoint00000/
    domain.h5
  checkpoint00001/
    domain.h5
```

**Comment by ecoon** [comment]
@lipnikov @jd-moulton @ajkhattak @dasvyat

**Comment by jd-moulton** [comment]
It would be good to have a brainstorming session about the design and consideration for some sort of hybrid memory model that may use threads.  The reason being that MPI communicators are fairly heavy objects and while there's trade offs on memory and such as to how many you might really get, most MPI libraries are built with hard coded max (e.g., 4K or 8K).  While this might sound like a lot, bigger meshes on larger number of cores could easily run into scaling problems.

**Comment by ecoon** [comment]
That's a good point, but a bit ambitious for what I'm going after now, which would be at most a few tens of watersheds.  The column concept could grow into that space, but we would need an entirely new linear algebra package (the whole point of this is to do solves, so we need vectors, which at least currently all need Epetra).

**Comment by lipnikov** [comment]
In addition to checkpoints we have visualization files that are already suffixed with mesh names. In both cases io is quite similar. Will the suggested modification touch visualization? If so, will VisIt work?

**Comment by ecoon** [comment]
the XDMF format is set with one mesh per file, so yes, this makes checkpointing more like vis.  The difference is that currently vis can be done independently -- you can say "visualize the surface mesh every X days and the subsurface mesh every Y days" whereas it doesn't make sense to allow this for checkpoints.  Checkpoints are all or nothing (you can't restart unless you have all).

These changes won't affect vis at all for now.  I'll make sure, but I think vis is already created with the mesh's communicator, so there should be no issues.

**Comment by lipnikov** [comment]
If you have too many files then check_meshname_000XXX.h5  does not look easy manageable and your layout is great. But if you have only check_domain_*, check_surface_*, and check_fracture_*,  then the new layout does not provide many benefits. Ultimately, I prefer to have common i/o code, so if PI is okay, I have no objections to the tree-based layout.

**Comment by ecoon** [comment]
Agreed, there is no advantage (arguably disadvantage) if all meshes exist on MPI_COMM_WORLD.  For now I think we can keep the current "one file" approach as the default, and throw an error if the COMMs don't match.  Then setting a "single file checkpoint"=false parameter switches to the "new" style.

**Comment by raovgarimella** [comment]
Just getting to this now. In principle, AmanziMesh and MSTK_Mesh and MSTK are supposed to work correctly with a sub-communicator and you should be able to have several of them co-exist. In practice, I am not going to offer up my first-born as guarantee that there are no calls to MPI functions which go out MPI_COMM_WORLD - however, they can most likely be fixed with little heartburn.

________________________________

**Comment by ecoon** [comment]
Checkpointing in multiple files is now supported.
