### ISSUE TITLE
missing default constructor in BilinearForm?

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#518]
Recent changes leave Amanzi unable to compile on my machines.

MFD3D has a default constructor, and inherits from BilinearForm.  MFD3D's default constructor does not explicitly call BilinearForm's constructor (which takes a MeshLight object).  Since BilinearForm implements a constructor (that with a MeshLight) and does not declare explicitly a default constructor, this is a compile error.

Either BilinearForm needs a default constructor, or MFD3D needs to call BilinearForm's constructor with a MeshLight.

**Comment by ecoon** [comment]
Hmm, this hasn't changed recently.  I'm not sure why this ever compiled though -- I'm using a fairly standard, if old, gcc (5.x).

The reason it "works" is the virtual inheritance used in MFD3D, e.g.

    class MFD3D : virtual public BilinearForm;

MFD3D's constructor, since it is virtual inheritance, must call BilinearForm's constructor _explicitly_.  But it doesn't.

I don't actually see why MFD3D should inherit virtually.  Is there a diamond pattern here?

**Comment by lipnikov** [comment]
Diamond pattern was removed some time back.

**Comment by ecoon** [comment]
I just added a branch that fixes it for me.  Testing on the machine that broke now.

**Comment by ecoon** [comment]
will also check your fix to confirm, then remove my branch assuming things work.

**Comment by lipnikov** [comment]
Sorry for duplicated work, but you assigned it to me.

**Comment by ecoon** [comment]
No worries, I was just trying to get something compiling.  I wasn't sure my first guess was right.
