### ISSUE TITLE
Clear out many new Vector allocations in GMRES

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#527]
The Krylov space is resized and assigned to null, deallocating the Vectors, at the start of each GMRES call.  The vectors are also newed each GMRES call in the algorithm.  Furthermore, work vectors w,p,r are all created each call.  That's a lot of memory that is used -- krylov_space + 4 vectors created each call.

I think this memory should likely stay persistent from call to call.  Especially the Krylov space vectors -- at least the workspace is freed between calls, but the Krylov space vectors are freed immediately before the next new.

**Comment by ecoon** [comment]
Need to check other Krylov space methods to see if they have the same problem, and see if it makes sense to reallocate the workspace vectors r, w, and p each step as well.

**Comment by lipnikov** [comment]
Does it worth to do mini-management of local variables r, w, p? It reduces code readability and may be negligent compared to the cost of orthogonalization.

**Comment by ecoon** [comment]
See #529.  The problem probably wasn't the allocation of memory, but the re-creation of the Epetra_Imports for Scatter/Gather operations.

The Krylov vectors were stored though.  We were deallocating them in the `v_.resize(krylov_dim_+1, Teuchos::null)` call immediately prior to calling GMRES_(), which then allocated them as the space grew.  So there was no memory savings at all, and 10ish vectors free'd and alloc'd every ApplyInverse.

**Comment by lipnikov** [comment]
I do not like that caching everything is the new way of doing things. I agree that Krylov space could be created only once for multiple restarts of GMRES, but I cannot support keeping this work memory around then ApplyInverse is done. For a bad preconditioner, we may need hundreds of Krylov vectors.

**Comment by ecoon** [comment]
Sure, that works.

**Comment by ecoon** [comment]
closed by the above commit and pull request.
