### ISSUE TITLE
performance problems in MPI

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#529]
So it turns out that construction of an Epetra_Import, the object that is used to import one data structure into another (e.g. for scatter/gather operations on Epetra_Vectors) is a non-trivial, not cheap operation.  (Not cheap in that it takes multiple collective operations, and maybe even an All-to-All).

All Cell-based vectors on the same mesh share the same Epetra_Map (well, not literally, but they are shallow copies of each other because they store a "smart" pointer of the data internally).  Then, all CompositeVectors get their Cell map from the Mesh, via mesh.cell_map().  So we all use the same map for both ghosted and local vectors.

But we don't use the same Importer -- that gets created, on demand, in the CompositeVector.  Furthermore, those importers were not shared on copy construction of CompositeVector.  Moral of the story -- in a relatively small run on NERSC, 32 cores using gnu + MPICH, a profile shows that MPI_Barrier was taking 33% of the time, and MPI operations on the whole were taking 60% of the time.

Some digging suggested that the problem was a bunch of construction of Epetra_Imports.  There are a variety of ways to "fix" the problem, and one way to "really fix it."

1. The copy constructor of CompositeVector should copy over the Importers if they exist.  We should use the same Import.
2. Client code shouldn't construct work space vectors from maps.  Constructing them from maps mean we don't have the importer to copy from another vector.  Furthermore, they could (probably should, though maybe @lipnikov doesn't agree in all cases) store their workspace rather than mallocing new vectors every timestep like GMRES, NKA, and probably all of our solvers do currently.  See #527 for an example of a particularly bad case, where the entire Krylov space was getting destroyed and immediately reconstructed every solve.

But the "better way" is probably to have the mesh keep the importers in addition to the map, and return those for use by all vectors.  Then, any vector constructed with the same mesh would share one importer per entity kind.

**Comment by lipnikov** [comment]
Regarding GMRES, you making a horror story ;-) without solid facts. The cost of orthogonalization could be huge compared to allocation of a new Krylov vector and applying preconditioner to it. The internal memory should be released after GMRES  is done, so your statement is not clear. Do you want to keep the internal memory for all persistent iterative solvers?

**Comment by lipnikov** [comment]
I think some Amanzi algorithms already try to re-use importers for exactly the same reason. Great if support of importers will be the integral part of CV.

**Comment by ecoon** [comment]
So if we're going to allow temporaries, then I think we have to either always construct temporaries from the copy constructor (this seems fragile) or get the importer from the mesh, which should be more robust.  On the run I'm profiling, removing all temporaries from GMRES and NKA (and PDE_DiffusionFV) so that Epetra_Import's constructor was only called in Cycle 1 worked great -- it halved the runtime on a 32 core job with.  (Just some facts for you ;) )

**Comment by ecoon** [comment]
@JulienLoiseau If you have a few minutes tomorrow (Friday) I'd like to see if you have ideas on how to answer the question, "what are the cores not at the barrier doing while some cores are sitting at an MPI_Barrier?"

**Comment by lipnikov** [comment]
Factor 2 is fantastic. I studied the design of Epetra_Import and is not surprised by its cost. But if the copy constructor copies pointers to importer the cost is no longer the issue. Why do you think that the copy constructor could be fragile?

**Comment by lipnikov** [comment]
When we partition cells evenly, we do not partition faces evenly. So some load balancing is unavoidable in FV schemes. What big is imbalance between owned faces?

**Comment by ecoon** [comment]
> Factor 2 is fantastic. I studied the design of Epetra_Import and is not surprised by its cost. But if the copy constructor copies pointers to importer the cost is no longer the issue. Why do you think that the copy constructor could be fragile?

The copy constructor fix is fragile because creating a CV can also be done from a map.  See https://github.com/amanzi/amanzi/blob/master/src/operators/PDE_DiffusionFV.cc#L502 for an example of a temporary which would always be creating a new Importer.  Putting the importer in the mesh fixes both cases.

> When we partition cells evenly, we do not partition faces evenly. So some load balancing is unavoidable in FV schemes. How big is imbalance between owned faces?

Oooh, good point.  I hope that isn't the case.  40% is a lot of wasted time.  I'm still hoping it is face_get_cells!

**Comment by ecoon** [comment]
I have both a Map profile and a perftools profile that I will upload tomorrow.  Hopefully someone with a bit more skill at reading these will have some ideas on how to tease out the lost time.

Of course, we should also check the ApplyInverseAssembled version.  It's possible that will simply be faster at this point.

**Comment by lipnikov** [comment]
I see your point now. But the new importer should be identical to that in other similar CVs. I also agree that if we could take importer from the mesh in all cases, this would be better solution. 

BTW, SuperMap is used to construct a vector. This is one example of constructing a workspace vector form a map.

**Comment by ecoon** [comment]
SuperMap constructs an Epetra_Vector, and doesn't create ghosted vectors.  The Epetra_Import used for Scatter/Gather operations on that vector comes from the Epetra_CrsMatrix's row/column maps, and is constructed by and stored in the matrix.  So we don't have to worry about that one.

**Comment by ecoon** [comment]
Some more info:

```
ATS Mesh Factory   |   Creating mesh "domain" of type "read mesh file".
ATS Mesh Factory   |     Load Imbalance: (min, mean, max)
ATS Mesh Factory   |       CELLS: 3515, 3528, 3534
ATS Mesh Factory   |       FACES: 8888, 9067, 9629
ATS Mesh Factory   |   Creating mesh "surface" of type "surface".
ATS Mesh Factory   |     extracted from "domain".
ATS Mesh Factory   |     Registered mesh "surface".
ATS Mesh Factory   |     Registered mesh "surface_3d".
ATS Mesh Factory   |     Load Imbalance: (min, mean, max)
ATS Mesh Factory   |       CELLS: 185, 185, 186
ATS Mesh Factory   |       FACES: 272, 281, 311
```

So if we assume all face_get_cell() and local matrix-vector products using the resulting face-based stencil are equal, then one would expect the worst process to take 9629 units and the fastest processes to take 8888 units, and using a mean of 9067 makes for inefficiency of only 6%.  So that doesn't quite seem enough to explain such a bad load imbalance to me.

**Comment by lipnikov** [comment]
Interesting. Imbalance could be also attributed to the communication pattern in Epetra_Import. We can expect that processes with lower rank are generating and sending more packets. But probably this will be not enough to cover for 40%

**Comment by ecoon** [comment]
Trace-based profiling shows that the time in Barrier is not as bad as the random-sampling-based profiling suggested.  This likely should get revisited again after a mesh refactor.

However, it also suggests that there may be faster performance if we could use ApplyAssembled() when the matrix has already been assembled.

**Comment by ecoon** [comment]
closing this, will make a new ticket for ApplyAssembled()
