### ISSUE TITLE
TPLs collection on software.lanl.gov is unavailable.

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#53]
Due to cyber-security concerns, software.lanl.gov is being shutdown.  This was a convenient place to host our TPLs, and so we are in search of a solution.  Updates in CMake provide the option for listing multiple URLs for a given tarball, and eventually we'll want to take advantage of this feature.  In the short term we are looking for a hybrid solution of a repository (amanzi-tpls), and direct downloads from mirrors.

**Comment by ecoon** [comment]
I think we can close this?

**Comment by jd-moulton** [comment]
Yes, this is working.  Additional updates are likely to help support Docker containers and Travis-CI.  But this initial phase is done.
