### ISSUE TITLE
performance problems in mesh.face_get_cells()

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#530]
A recent profile of ATS on NERSC shows mesh.face_get_cells() taking nearly 10% of runtime on a 32 core, 100K cell problem.  This is kinda bad.

I'm addressing this more formally in the mesh refactor discussed in #499, but we may need to put a band-aid on the current Mesh infrastructure for reasonable performance.

**Comment by lipnikov** [comment]
On Amanzi size, this function is called for OWNED faces in 11 places, after I removed two. 80% of the remaining cases are related to the code that @ecoon knows better.

**Comment by lipnikov** [comment]
Mesh classes were refactored... closing this as outdated.
