### ISSUE TITLE
allow state-initialized variables to include domain set values

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#533]
Update state-initialized variables to allow domain-set initializers in there, e.g. "subgrid:*-sorbed_kd"

**Comment by ecoon** [comment]
Should get updated here: 

https://github.com/amanzi/amanzi/blob/master/src/state/State.cc#L1070

**Comment by ajkhattak** [comment]
I have not started to work on this, but it's on my todo list, and will come to it asap.

**Comment by smolins** [comment]
What is the time frame for this @ajkhattak?
