### ISSUE TITLE
bug in concepts/usage of Whetstone support operator

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#545]
@lipnikov I've been running into so slow runs and tried to run all MFD discretizations on a mesh recently to check if they were all slow.  Support operator crashed with the following error:

"WhetStone MFD3D_Diffusion: number of faces forming a corner is small."

which is thrown here: https://github.com/amanzi/amanzi/blob/master/src/whetstone/MFD3D_Diffusion_Other.cc#L134

if the number of faces in a cell adjacent to a node is less than the space dimension of the mesh.  This is not possible in our mesh, so I ran it through the debugger.

It appears that WhetStoneMeshUtils::node_get_cell_faces() has hard-coded into it to only get OWNED faces, not ALL faces, despite the PTYPE=ALL passed to this call.  So while the cell is owned, the common faces that touches that node is not OWNED, and the result is a node who has 2 OWNED faces but 3 ALL faces, triggering the error message.

So I believe that this implementation will crash on all triangular prism meshes in parallel.

**Comment by lipnikov** [comment]
You already solver the problem.  There is something weird about loop over cells...

**Comment by ecoon** [comment]
I didn't want to fix it because I wasn't sure whether the check for "if f > nfaces_owned continue" was a bug or on purpose -- it seemed too specific to be on accident!

**Comment by lipnikov** [comment]
The conclusion is to write more tests ;-)
