### ISSUE TITLE
error message in logical regions spec 2.3.0 (but not in native spec)

### ISSUE THREAD

**Issue by smolins** [amanzi/amanzi#548]
The 2.3.0-to-native Amanzi translator does not seem to understand the operation element for logical regions. Is this a bug or is the documentation incomplete/incorrect or misunderstood by me. I get the expected behavior from the native spec. 

**Error message**

InputConverter2.3  |  Translating units: m s kg molar K
InputConverter2.3  |  Translating unstructured mesh
InputConverter2.3  |  Translating regions
An error occurred during parsing high-level node "regions"
No element "operation" found for sub-node "logical".

Amanzi::SIMULATION_FAILED

**From input schema 2.3.0 (https://amanzi.github.io/amanzi/UserGuide/input/input_schema.html#logical)**

Logical regions are compound regions formed from other primitive type regions using boolean operations. Supported operators are union, intersection, subtraction and complement. This region type is only valid for the unstructured algorithm.

```xml
<logical name="logical name" operation="union | intersection | subtraction | complement" region_list="region1, region2, region3"/>
```

**Relevant portion of Input file that leads to error message**

```xml
 <mesh framework="mstk">
    <comments>pseudo 3D</comments>
    <dimension>3</dimension>
    <generate>
      <number_of_cells nx = "200"  ny = "200"  nz = "1"/>
      <box  low_coordinates = "0.0,0.0,0.0" high_coordinates = "200.0,200.0,1.0"/>
    </generate>
  </mesh>

  <regions>
    <region name ="All">
      <box low_coordinates= "0.0,0.0,0.0"     high_coordinates="200.0,200.0,1.0"/>
    </region>
    <region name ="smallbox">
      <box low_coordinates= "100.0,0.0,0.0"     high_coordinates="150.0,200.0,1.0"/>
    </region>
    <logical name="bigbox3" operation="subtraction" region_list="All,smallbox"/>    
  </regions>
```

**Equivalent native spec version that works**

```xml
    <ParameterList name="bigbox3">
      <ParameterList name="region: logical">
        <Parameter name="operation" type="string" value="subtract"/>
        <Parameter name="regions" type="Array(string)" value="{All,smallbox}"/>
      </ParameterList>
    </ParameterList>
```

**Comment by lipnikov** [comment]
The unit tests indicates different structure, which seems consistent with the schema. I'll run it again through the schema and update the 2.3.x documentation. Thanks.
 
   <logical name="Total_Recharge">
      <operation>union</operation>
      <region_list>Recharge_Boundary_WestOfCrib, Recharge_Boundary_EastOfCrib</region_list>
    </logical>
