### ISSUE TITLE
valid_set_name() issues

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#558]
Some work on CompositeVectorFunction() to allow it to work in simpler ways and remove some dead code has exposed some potential issues in Mesh::valid_set_name().
 
First of all, the case of BOUNDARY_FACE is not handled in valid_set_name() at all.  So that is a bug that needs to be fixed, and is easily done.  Edges aren't handled either in this code, so it would be good to do that as well.

Second, I'm not sure what I think about the topological dimension testing.  At various points we have used 3D regions, e.g. a box, to identify a specific set of faces on real meshes where planes cannot work.  Most of the time we then intersect that box with the boundary, but logically at least, to intersect the regions you need two valid sets, at which point you can take the (discrete) intersection of the entries in those regions.  So a user might go into VisIt, determine a box which contains the faces of some patch you want to impose a boundary condition or observation on, then intersect that "region: box" with a "region: boundary" to get the boundary faces in that box, and use that for your BC or observation.

Currently I <s>suspect that should</s> _have confirmed that it does_ fail because "region: box" with 3D coordinates on entity_kind == FACE should fail the test here for valid_set_name().

https://github.com/amanzi/amanzi/blame/master/src/mesh/Mesh_Sets.cc#L102

**Comment by ecoon** [comment]
Ok, it seems that more than a few things now fail, that used to work, for BOUNDARY_FACE.  get_set_size() also fails with error "Count requested for unknown entity type."

**Comment by ecoon** [comment]
So that leaves the last question -- should it be valid to select entity_kind = FACE using a 3D box?

@lipnikov @jd-moulton thoughts?

**Comment by lipnikov** [comment]
Box defines a region. From this region, we potentially can request all mesh objects: cell, face, edge, or node.

**Comment by ecoon** [comment]
While you probably can request the set, the check for 

    valid_set_name("my_3d_box_region", FACE, ALL)

fails, because there are topological dimension checks at the line of code linked in my first post, that ensure that the region's dimension is 1 less than the mesh's dimension.

**Comment by ecoon** [comment]
And the case of EDGE isn't handled at all in valid_set_name()

**Comment by ecoon** [comment]
Ugh, wait, maybe this is my mistake -- that line of code reads >= so 3D should be fine.  Why is my test failing then?

**Comment by ecoon** [comment]
Ok, so the problem in my test for FACE in a "region: box" was my mistake in updating the test (some confusing code in test_hex_3x3x3_sets.cc didn't help the matter, but oh well).  So, in summary:

1. valid_set_name(*, EDGE,*) will always return false.  Likely this should change sometime.
2. valid_set_name(*, BOUNDARY_FACE, *) will also always return false.  Really BOUNDARY_FACE does not appear to be supported as a valid entity for use with sets at all right now (this will change in ecoon/mesh_refactor).
3. We don't appear to have very uniform testing of sets, and I don't see any tests of 2D meshes with sets?

Closing for now, because the immediate "bug" wasn't so much a bug as my incorrect assumption that we could use BOUNDARY_FACE with sets.  I will still refer back to this issue on mesh refactor, however, as I will update tests and ensure that BOUNDARY_FACE is a valid entity for using with sets.
