### ISSUE TITLE
Boost shared libraries broken on OSX (and maybe Ubuntu)

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#560]
On OSX the dynamic libraries for boost that we install with our TPL build includes a runtime path pointing back to the build directory instead of the install directory.   As soon as you remove your build directory for your TPLs this is broken. 

On Ubuntu 18.04, it appears the runtime path in the boost shared libraries is not set, and so our installed libraries can't be found.  

We need to consider updating boost while we address the runtime library path issues. 

**Update:** On Cori and Ubuntu, the boost shared libraries do not have the rpath/runpath set.  However, since they are installed in the same location as other libraries, the amanzi binary is able to find them.  The problem on OSX is the rpath is set, but it is incorrect, so that is really broken.

**Comment by lipnikov** [comment]
../lib/libboost_graph.dylib:
	@rpath/libboost_graph.dylib (compatibility version 0.0.0, current version 0.0.0)
 
Looks correct in OSX 10.14 and native clang

**Comment by jd-moulton** [comment]
With macports on OSX 10.15 (XCode 11.x) I get

```
moulton@pn2003009 lib % otool -L libboost_regex.dylib
libboost_regex.dylib:
	/ascem/amanzi/tpls/builds/openmpi-4-gcc-10-TPLs-0.98.0-shared/boost/boost-1.67.0-build/boost/bin.v2/libs/regex/build/gcc-10.3.0/release/threading-multi/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.28.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
Any thoughts on where this might be going wrong?

**Comment by lipnikov** [comment]
FYI: Long time back (2-3 years) I did not resolve all gcc related issues with the current and the next versions of Boost. I think it was due to limited support of gcc toolset on OSX.

**Comment by jd-moulton** [comment]
I do vaguely remember this wasn't completely resolved.   I will dig a little deeper and possibly try a new boost.  Can you check how it looks for you on Linux?   My builds on our T-5 systems are a little suspect, e.g., boost doesn't seem to get runtime paths correct there either (they are just missing):

```
piquillo4(143)$ ldd libboost_filesystem.so
	linux-vdso.so.1 (0x00007ffda6cda000)
	libboost_system.so.1.67.0 => not found
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00001466c1926000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00001466c159d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00001466c11ff000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00001466c0fe7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00001466c0dc8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00001466c09d7000)
	/lib64/ld-linux-x86-64.so.2 (0x00001466c1d4a000)
```

**Comment by lipnikov** [comment]
Same on HPC system: 
ldd .../TPLs-0.98.0-openmpi-3.1.6-gcc-9.3.0-shared/lib/libboost_graph.so
   libboost_regex.so.1.67.0 => not found

**Comment by lipnikov** [comment]
Boost will be removed, see #561
