### ISSUE TITLE
Migrate away from boost

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#561]
We use very little of boost, and it is a pain to maintain.  Let's migrate away from it slowly.

**Comment by lipnikov** [comment]
I removed boost from the code that I contributed, except for boost::format. The ball is in your court now.

**Comment by ecoon** [comment]
Please don't do this kind of infrastructure change without a pull request.  By removing boost functionality from Amanzi master without running ATS tests or checking ATS CI, I have to drop all other work and fix ATS master before anyone can do anything.

**Comment by lipnikov** [comment]
Since I did not remove Boost functionality, just replaced a few calls, the existing Amanzi tests should be sufficient. Are you saying that these tests do not cover critical code base? I am confused... I do not see any ATS commits related to recent changes.
