### ISSUE TITLE
bug in verify_operators for multiple repetitions

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#563]
in both the master and tpetra versions of this test, src/operators/test/DiffusionFixture.hh has a bug --

https://github.com/amanzi/amanzi/blob/master/src/operators/test/DiffusionFixture.hh#L182

the PutScalar() here needs to be moved out of setup and into the Go() method, to allow for multiple calls to Go() for one call to Setup().  Otherwise the solution is still the same value as the previous solve, so the second loop of Go() always converges in no iterations because it is already the converged solution.  That line should move to after this line:

https://github.com/amanzi/amanzi/blob/master/src/operators/test/DiffusionFixture.hh#L334

**Comment by lipnikov** [comment]
This is the design required for NLFV schemes. No action is needed at the moment.

**Comment by ecoon** [comment]
Presumably the nloops option for verify_operators was intended to allow multiple solves to give better numbers for timing.  As it stands nloops gives a solve the first loop and a no op all successive loops so the timing info is worthless.

**Comment by lipnikov** [comment]
nloops was originally introduced for nonlinear FV schemes.  If you need to repeat the same solver multiple times, an additional input parameter is needed.
