### ISSUE TITLE
add option to turn off DBC in bootstrap

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#565]
Should this option also be turned off when build type == Release by default?

**Comment by ecoon** [comment]
Ok, I just pushed a bootstrap option to disable.  By default this is always TRUE, even for Release builds.  Checking the runtimes, turning off DBC saves ~3% runtime on an optimized build, so clearly this isn't mission critical.  But I do think as developers we should strive to not use ASSERT for user errors and eventually turn off DBC for Release builds.

**Comment by ecoon** [comment]
@jd-moulton up to you whether you think we should leave this as TRUE on Release or not.

**Comment by lipnikov** [comment]
In my opinion, before usage of ASSERT is cleaned up DBC should be set to true.

**Comment by ecoon** [comment]
Default is left for TRUE for now.  May reopen once ASSERT usage is cleaned up.
