### ISSUE TITLE
AMANZI-TPLS netcdf-fortran library installation path inconsistency on Linux OS

### ISSUE THREAD

**Issue by fmyuan** [amanzi/amanzi#584]
In an ORNL cluster, we found that AMANZI-TPLS intalled netcdf-fortran library, libnetcdff.so, is installed under $AMANZI-TPLS_DIR/lib64, while its dependent library of netcdf-c, libnetcdf.so, is under $AMANZI-TPLS_DIR/lib. 

The netcdf-fortran library path is inconsistent with what 'nf-config --flibs`, which refers to $AMANZI-TPLS_DIR/lib. And this may cause library not found error, if using 'nf-config --flibs' or 'nc-config --flibs' for library search.

It's likely it is a bug in installation stage, for Linux OS.

**Comment by jd-moulton** [comment]
Thank for pointing this out.  It shouldn't cause any problems with Amanzi and ATS builds, but if someone tries to reuse these libraries in other codes it's possible.   Its also a little strange that netcdf-fortran insists on this installation directory.  We'll look into fixing it.

**Comment by lipnikov** [comment]
Potentially CMAKE_INSTALL_LIBDIR returned by GNUInstallDirs points to lib64 which is mentioned in the CMake documentation. We could try to overwrite this CMake variable.
