### ISSUE TITLE
Bootstrap fails with non-standard location of MPI

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#587]
Bootstrap fails to run Amanzi tests when MPI is locates in a non-standard directory. MPI_EXEC is undefined. Environmental variables have no MPI.  Location of MPI is provided via bootstrap options.

**Comment by JulienLoiseau** [comment]
@ecoon Was that something you changed to be able to run on Summit? (with the jsrun)

**Comment by lipnikov** [comment]
I think bootstrap either needs this input parameter for configuring Amanzi or better configuration of FindMPI in internal scripts.
```
-D MPI_EXEC:FILEPATH= 
```

**Comment by ecoon** [comment]
I manually changed the MPI_EXEC variables in the CMakeCache afterwards (because I didnt' want to rebuild TPLs).  I think these are options that can be passed into CMake and used, but I'm not sure how bootstrap supports this now.  Is there a generic option for dumping stuff into the configure script?  Maybe there should be?

```boostrap.sh --amanzi-configure-args="-DMPI_EXEC=..."```

**Comment by lipnikov** [comment]
Since we already provide non-standard mpi location to bootstrap, we could use MPI_HOME variable for FindMPI. Make says 
it could be used to "Specify the base directory of the MPI installation."

**Comment by lipnikov** [comment]
--amanzi-configure-args could be a good option for Amanzi experts.

**Comment by ecoon** [comment]
What flags are you passing bootstrap?  To be honest this has always confused me a bit.

In my builds, I always end up providing BOTH

--with-c-compiler=`which mpicc` (and mpicxx and mpifort)

AND

--with-mpi=/path/to/mpi_dir

On my mac, that actually ends up pointing in two different places -- /usr/local/bin/mpicc and /usr/local/Cellar/open-mpi/VERSION -- though the MPI wrappers in /usr/local/bin are soft-links to /usr/local/Cellar/open-mpi/VERSION/bin

The reason I've always had to do both (which seems odd to me) is that PETSc doesn't like wrappers and wants the --with-mpi= directory, but the compilers don't get set right if I don't also provide those options (they get set to clang and not mpicc, and this fails for not being able to compile MPI).

If we're fixing things to look in MPI_DIR/bin for mpiexec, we might also look for mpicc, etc if compiler options are not given to bootstrap.  It would be nice to just have to provide --with-mpi and not compilers.

--amanzi-configure-args="-DMPI_EXEC_GLOBAL_ARGS=--oversubscribe"

yes please!

**Comment by ecoon** [comment]
I will add "--amanzi-configure-args" and "--tpl-configure-args" on #590

**Comment by lipnikov** [comment]
If I remember correctly, we did not want to perform too many checks inside bootstrap, such as if a compiler is MPI capable or not. For this reason --with-mpi was added.

**Comment by jd-moulton** [comment]
There's a lot of history and cruft in our internal FindMPI related logic.   We should see to what extent the FindMPI.cmake that comes with recent versions of CMake fixes some of the original issues, and see what options we need.   Probably updating and tweaking is most sustainable approach.  

I agree the --oversubscribe option has been needed for a while, and there really shouldn't be any issue finding mpiexec given the installation directory --with-mpi.    So even with the cruft the original motivation for this issue could probably be fixed fairly easily.   I will try to look into this next week.

**Comment by jd-moulton** [comment]
@lipnikov Can you provide more details about the system you have this problem on?  Is it Darwin or another system that I might have access to?  Despite the cruft that's around we do use the FindMPI module provided by CMake, so this is something that should be straightforward to fix.  Also, do you provide the --with-mpi option or compilers?

**Comment by lipnikov** [comment]
OSX 10.14.6. The bootstrap options are (a) --with-*-mpi*  (3 MPI supporting compilers) and (b) --with-mpi=/root/mpi/installation
