### ISSUE TITLE
Ghosted field is not populated for independent evaluator

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#589]
processListWithFunction() returns random ghosted value (bool) for variable space. This information propagates and affects initialization of independent evaluators.

**Comment by lipnikov** [comment]
Apparently the problem is more complex. The only time test passes, if I initialize ghosted(false) in the constructor of PatchSpace.

**Comment by ecoon** [comment]
Yes, that's right.  It should be default false I think, under the paradigm of "do the work on owned entities, then communicate if needed."  These patches get used to populate composite vectors, or to be boundary conditions, so it makes sense that there are times it could be either ghosted or owned.  So you can construct a ghosted or non-ghosted patch, but I think the default should be false.  In the case of MeshFunctions, I think it makes sense to be false.

**Comment by lipnikov** [comment]
The problem is that this constructor uses already ghosted(ghosted_), so what I did as a test was changing the logic.

**Comment by ecoon** [comment]
It looked to me like the mesh function processing used the default constructor:

https://github.com/amanzi/amanzi/blob/tpetra-solvers/src/mesh_functions/MeshFunction.cc#L178

which left "ghosted" uninitialized, then used AddPatch() to push back patches which were constructed from the MultiPatchSpace's ghosted (the uninitialized one).

**Comment by ecoon** [comment]
I believe this should be closed by 0b1b1b20ad47b8abf61ab7d38bf2d1c3cd947f0d

Let me know if you still see issues -- I ran the test 10 times and it passed all 10, but it also passed for me prior to this change.

**Comment by lipnikov** [comment]
The test passed. This also helped a few other failing tests.
