### ISSUE TITLE
missing test file fracture.exo

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#59]
commit 5ecd1536ae6f1a87aa656324f38e1dcf9cac118a added a new test, test_nonmanifold_surfaces.cc, but is missing some supporting mesh files -- at least one called fracture.exo.  Maybe more?

Rao, can you add this and any other new files needed for testing?

Thanks, glad to see this getting fleshed out more!

**Comment by ecoon** [comment]
Closed by commit 04300dddc

Might actually have been closed before I opened it!

**Comment by raovgarimella** [comment]
Yeah, man, around here we move faster than the speed of light.
