### ISSUE TITLE
Observation with multiple components

### ISSUE THREAD

**Issue by dasvyat** [amanzi/amanzi#594]
What is the logic behind creation of the field with observations?

https://github.com/amanzi/amanzi/blob/033b40d4386ad7af74b25c7cf261975a88c86ce8/src/state/Observable.cc#L98

The number of vectors maybe either unknown or should be consistent with pk list.
The created vector belongs to state and can be in conflict with pk requirements.
num_vectors_ can be obtained from already created vector.

**Comment by dasvyat** [comment]
But currently observation creates these fields first, before PKs and declare ownership to "state". Am I right?

**Comment by ecoon** [comment]
No, it calls RequireField(name) with no owner, and AddComponent() as opposed to SetComponent():
https://github.com/amanzi/amanzi/blob/master/src/state/Observable.cc#L98

This ensures that the fields stay un-owned, so can be claimed by the evaluator or PK.

But agreed that it does create the field first, so will not be able to know whether a PK/eval will set num_vectors later as written.  I'm fixing this -- mostly done already -- by adding a Setup() stage to observations and a last lazy check to set the number of vectors if it hasn't been done prior to doing the first observation.

To confirm -- the symptom here is that you tried to observe a field with multiple DoFs (eg. concentration) without providing the "number of vectors" parameter in the observation and it crashed?

**Comment by ecoon** [comment]
Assuming that is the symptom, this is now fixed, and tested: https://github.com/amanzi/ats-regression-tests/blob/master/07_reactive_transport/surface_denitrification.xml#L286

**Comment by ecoon** [comment]
@dasvyat feel free to reopen and provide more info if this does not fix the problem you had

**Comment by lipnikov** [comment]
@ecoon The state tests are broken.

**Comment by lipnikov** [comment]
Fixed now.
