### ISSUE TITLE
Incomplete testing, inconsistent capability in MeshExtractedManifold

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#596]
In standardizing testing across a variety of ways of creating meshes, I've come across a few issues in MeshExtractedManifold.

1. If called via the MeshFactory, the flattened parameter is not passed here: https://github.com/amanzi/amanzi/blob/master/src/mesh/mesh_factory/MeshFactory.cc#L384  This has been fixed in #592 
2. In the case of flattened == true, calling `MeshExtractedManifold::face_normal(f, false, cellid);` gives the wrong answer.  Directions are not correctly implemented here: https://github.com/amanzi/amanzi/blob/master/src/mesh/mesh_extracted/MeshExtractedManifold.cc#L155 and the direction given here is used for the space_dimension() == manifold_dimension() == 2 case here: https://github.com/amanzi/amanzi/blob/master/src/mesh/Mesh.cc#L332 
3. Does this test pass?  https://github.com/amanzi/amanzi/blob/master/src/mesh/mesh_extracted/test/mesh_extracted_fracture.cc#L68  How can it pass given that MOAB does not support edges but MeshExtractedManifold requires edges?
4. It ought to be fairly trivial to add support for multiple sets in MeshExtractedManifold, and this would be convenient for more general usage.
5. In the case of flattened==True, building geometric sets does not work correctly.  It tries to query the set's inside() method with points from the parent mesh, but these may be of a different dimension.  For instance, getting a 2D box region on the surface flattened mesh queries the inside() method with 3D points from the parent mesh, which errors.

**Comment by ecoon** [comment]
Note I have added some commented out code that could be uncommented and used to test each of these.

Specifically:

3. https://github.com/amanzi/amanzi/blob/5b37c472719ba3ecb6ff23279b89c5472584f341/src/mesh/test/mesh_fracture_extraction.cc#L205
4. https://github.com/amanzi/amanzi/blob/5b37c472719ba3ecb6ff23279b89c5472584f341/src/mesh/test/mesh_fracture_extraction.cc#L110
5. https://github.com/amanzi/amanzi/blob/5b37c472719ba3ecb6ff23279b89c5472584f341/src/mesh/test/mesh_surface_extraction.cc#L192

**Comment by ecoon** [comment]
Part 1 was fixed in #592 
Part 2 was fixed in #592, commit b0aeef64f16907741c0f71b48e6869c460efd138

**Comment by lipnikov** [comment]
Multiple sets: the assumption was that a logical region could be created on a fly.

**Comment by lipnikov** [comment]
Part 3: it is a placeholder/continuous reminder for completing MOAB framework.

**Comment by lipnikov** [comment]
Part 5: The idea was to query the parent mesh first, in case it already has a required set. Unfortunately, we have no such capability to say yes or no. So, the parent mesh tries to build it and fails. I'll replace it with try {} command.

**Comment by lipnikov** [comment]
@ecoon Fixed Part 4 and Part 5. Part 3 requires MOAB development. Not now.

**Comment by lipnikov** [comment]
The simple mesh framework supports edges after a recent commit. The mesh extraction test passes mesh audit.
