### ISSUE TITLE
water_ground_transition_depth parameter in land cover

### ISSUE THREAD

**Issue by dasvyat** [amanzi/amanzi#597]
water_ground_transition_depth parameter is nowhere properly defined (at least I couldn't find it).
It leads to randomly throwing of the assert at

https://github.com/amanzi/ats/blob/a108fc9fad0ef1205d78ef6fbdf261283b581bdb/src/pks/surface_balance/constitutive_relations/land_cover/seb_physics_funcs.cc#L466

**Comment by ecoon** [comment]
ummmmmmmmmm yes, this is bad.  I know I have a demo that is using this branch of the code.... how is that running?

**Comment by ecoon** [comment]
Looks like that was running on an old branch of the code that is now merged in, but the merge broke the name or lost something.  Will fix this in the next hour.

**Comment by ecoon** [comment]
This is an ATS bug, not an Amanzi bug, so migrating it to ATS
