### ISSUE TITLE
Remove prints from ASCEM-IO

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#599]
Remove/hide these silly informational prints from our TPL:

```
ASCEMIO_Info: Preferred group size is set to nprocs/numIOgroups (1/1)
ASCEMIO_Info: Preferred group size is set to 1
```

**Comment by ecoon** [comment]
Haha, yes please.

Honest question -- are we getting anything from ASCEM-IO other than a set of wrappers around HDF5?  I recognize that the intent was to allow hierarchichal parallel IO, but have we ever used this?  If I run a problem big enough to need better IO, I would likely switch to ADIOS or something similar that is maintained and used first.
