### ISSUE TITLE
Hypre configuration failed

### ISSUE THREAD

**Issue by yangys586** [amanzi/amanzi#602]
**I encountered the following error when installing hypre. How can I solve this problem? Thank you!**

configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /data/para-test/apps/BLAS-3.10.0/libblas.a
configure: error: in `/data/para-test/package/amanzi-amanzi-1.2.0/build/tpls/hypre/hypre-2.22.0-source/src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

![47f9513a106c62abcaa6bbe2a4bc4a8](https://user-images.githubusercontent.com/88887152/129439606-2759eecf-e8f9-4462-b40f-5233f1f87203.png)

**Comment by JulienLoiseau** [comment]
Hi @yangys586 

Could I have a bit more details on the installation: 
- what system?
- the list of bootstrap parameters? 
- What branch? 
- What modules? 

Thank you!

**Comment by lipnikov** [comment]
The problem could be with --with-lapack-lib='a' 'b' in Hypre's command

**Comment by lipnikov** [comment]
No response for long time.
