### ISSUE TITLE
update cmake/SuperBuild to use find_package(Python)

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#652]
Currently we use find_package(PythonInterp).  This has been deprecated since cmake 3.12, when find_package(Python) was introduced.  We require 3.13+ for Amanzi.

Furthermore, there is a FindPython in tools/cmake/Modules.  This looks ancient, probably is the original from 3.12.  But I don't think it is even used at this point.  

Can we pay someone to modernize all of this and just require like 3.18 or something modern-ish yet?

**Comment by ecoon** [comment]
On a separate note, we require different versions of CMake for SuperBuild (3.11) and Amanzi (3.13).  These could probably be made the same.

**Comment by jd-moulton** [comment]
Superseded by #700, which drops back to find\_package(PythonInterp) for now.  Also CMake version issue is addressed in #701.
