### ISSUE TITLE
Alquimia_PK accesses state in an inner loop

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#656]
Please don't access state in an inner loop.  State accesses (eg. GetEvaluator()->Update(), Get<CV>(), etc) should be done outside the inner loop to avoid map lookups, error handling, dynamic_cast calls, and all sorts of overhead that is meant to be amortized outside of the inner loop.

E.g. Alquimia_PK::CopyToAlquimia() does this, and probably others.  These should be removed and added as arguments to the function if needed.

**Comment by lipnikov** [comment]
@ecoon The list of fields is huge and few functions do it. How about initializing Chemistry internal pointers before the loop over cells? 

One of the reasons is that chemistry's beaker is expensive, so even if we make this change, which I support, we shall not see much impact in chemistry loaded simulations.

If CopyFiledstoNextStep is no longer needed, I suggest to erase it, see Alquimia_PK::CommitStep()

**Comment by lipnikov** [comment]
I'm closing it.
