### ISSUE TITLE
TPLs don't build with python3.9 (and maybe any 3.X?)

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#665]
PETSc 3.13 has a bug in that it uses the python function: `threading.Thread.isAlive` 

This was removed at some point and is now called `threading.Thread.is_alive`

PETSc has fixed this bug in 3.17 (probably much earlier, but I just looked at the latest).

To fix this we either need to patch or upgrade PETSc.

Note that new OSX only ships with python3, and building Exodus with python2 results in a exodus.py that is not usable for later workflow work.

**Comment by ecoon** [comment]
note that python2.X and python3.x supply the `is_alive` variant, while only python2.X supply the `isAlive` variant.  So there doesn't need to be logic here, just a simple patch.

**Comment by ecoon** [comment]
Whups.  The offending file/line is:

$PETSC_SRC_DIR/config/BuildSystem/script.py

Line 239 should read:

`if thread.is_alive():`

**Comment by bensworth** [comment]
isAlive works with up to python 3.7 I think (I just forced my installation to use python 3.7 and it works, while python 3.9 does not)
