### ISSUE TITLE
Xerces configuration issues

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#696]
Xerces on OSX may find unicode in Xcode directories, but this code does not have all headers used by Xerces. For instance uset.h is missing. A possible solution is to modify FindICU.cmake and add it to Amanzi CMake modules. Modification is to use unicode/uset.h instead of unicode/utypes.h for package identification purposes. Reported and tested by Naren Vohra.

**Comment by jd-moulton** [comment]
Need a bit more information, as I don't have this problem on my OSX.  In particular, the ICU that is found is in my macports installation, and everything works just fine.   So what version of OSX, which version of cmake, and where is the ICU library that Naren wants our build to find.

**Comment by lipnikov** [comment]
Recent OSX and Xcode, unicode is also installed via MacPorts. However, FindICU finds unicode in MacOSX12.3sdk...something and points ICU_INCLUDE_DIR to that location. But this location does not have headers that Xerces needs.

**Comment by jd-moulton** [comment]
@lipnikov Can you update status on this issue.   Did you find a work around, or did it disappear when you updated XCode?

**Comment by lipnikov** [comment]
I can no longer reproduce it.
