### ISSUE TITLE
pflotran repo has moved

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#699]
Pflotran is no longer at bitbucket, and is now at

https://gitlab.com/pflotran

TPLVersions points to bitbucket, so this needs to get fixed ASAP

**Comment by ecoon** [comment]
fixed on master, not when/if this breaks TPLs

**Comment by lipnikov** [comment]
PFLOTRAN from the new location works fine for chemistry unit tests on OSX, arm64.

**Comment by jd-moulton** [comment]
We will need to fix it on any release branches we plan to support (like 1.2 and 1.3 at least).
