### ISSUE TITLE
CMake minimum version for next release

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#701]
It looks like newest version is required by SEACAS, which sets the minimum version of 3.17.0.    It seems like we should at least be consistent with our TPLs and possibly go a little newer.  Also we should be consistent between TPLs (SuperBuild) and Amanzi, the current inconsistency was mentioned in #652.  

Since changing the minimum version may change behavior of some newer CMake policies we should decide quickly so we can test sufficiently before the release.

**Comment by lipnikov** [comment]
OSX works with 3.17, both intel and arm. I am using newer CMake for long time already.

**Comment by lipnikov** [comment]
Ubuntu 18.04 and Chicoma are fine with CMake 3.20. What is your concern?

**Comment by jd-moulton** [comment]
My objective is to stay current without forcing people to build cmake unnecessarily.   So new enough that we meet the requirements of the TPLs, but not too new.  Ubuntu 20.04 system cmake is 3.16, Ubuntu 22.04 has cmake 3.22.1.  So older systems are probably stuck regardless as SEACAS needs 3.17.0.

I think most of us are using CMake in the 3.22 range or possibly newer.   In other words I'm not concerned about newer CMake not working.   My understanding is that when new policies are created that change behavior in a newer version, the old behavior is still the default where old is determined by your minimum version.  So changing our minimum version may change the behavior of our builds.  We just need to test to be sure all is good.

**Comment by ecoon** [comment]
Definitely need to be the same between TPLs and Amanzi.  I don't care which version, and would prefer newer over older.  3.20 is on my homebrew currently, but I can go newer if that is what you want.

ATS sets no policies beyond Amanzi, so no concerns there.

**Comment by jd-moulton** [comment]
Another data point, Trilinos is about to switch main development to 3.22.

**Comment by lipnikov** [comment]
Does Trilinos plan to use features not available in 3.21 or before?

**Comment by jd-moulton** [comment]
After some debate it looks like we should be ok with 3.17.0 for a while as even the newer Trilinos we are using on the Tpetra branch is still at 3.17.0.   Also, we don't have any policies that we are setting to _old_ behavior so no issues there either.

**Comment by jd-moulton** [comment]
PS.  Updated the Docker image so it has cmake 3.17.0.
