### ISSUE TITLE
spatially/temporally variable, isotropic MDM

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#705]
@lipnikov  We would like to add the ability to do spatially and/or temporally variable, isotropic MDM coefficients.

To do this, we'll allow alpha in MDM_Isotropic to be a function.

This would require adding space and time arguments to the mech_dispersion() method.

Would you prefer that we:

1. add to the API, making a new virtual function that additionally accepts `double time, Point coord` arguments or 
2. modify the existing API including Amanzi transport PKs

Either way, we'll add to the potential input spec to allow for passing in a function argument in addition to the existing option of passing in a single double.

@levuvietphong

**Comment by lipnikov** [comment]
I think 2 gives more flexibility for future developments.
