### ISSUE TITLE
Mesh Refactors 

### ISSUE THREAD

**Issue by JulienLoiseau** [amanzi/amanzi#730]
These issues need to be adressed regarding the new Mesh Refactor: 

- [x] mesh_extracted_fracture.cc last doest work: mesh audit fails. 
- [ ] mesh_surface_extraction.cc last `MESH_SURFACE_EXTRACTION_EXO_EXTRACTED_MANIFOLD` tests commented: have trouble with the implementation: should the Mesh_Simple implement getEdgeFaces? Also test fails with `map.at` error for multiple ranks.  face_map has been replaced by a not initialized map. Design flaw.
```
Checking cell geometry ...
ERROR: found cells with non-positive volumes: 0 1 2
       Cells either geometrically degenerate or have bad topology.  Test failed!
```
- [x] whetston_surface.cc:124. The normals orientation doesnt make sense. 
- [ ] whestone_dg.cc: The normal orientation is also a problem inside `whetstone` in general.

**Comment by lipnikov** [comment]
whetstone_surface test was fixed on PR's branch.

**Comment by lipnikov** [comment]
whetstone_dg test requires probably more work on SingleFaceMesh class which has no cached data. The original design of BuildCache_() was modified for some reasons.

**Comment by lipnikov** [comment]
Edges must be requested/initialized in the parent mesh. I fixed that. Mesh audit now crashes.

**Comment by lipnikov** [comment]
Mesh::getCellFaces() calls getCellFacesAndDirs() with null pointers. Hence each class must handle the case of dirs=NULL

**Comment by lipnikov** [comment]
Refactory was completed.
