### ISSUE TITLE
Shallow water dry bed test not working correctly

### ISSUE THREAD

**Issue by nvohra0016** [amanzi/amanzi#775]
The test shallow_water_dry_bed is not working as it should. The test simulates a flooding scenario over a dry bed with non-zero bathymetry. However, the solution profile is not getting updated as the simulation progresses, and the test is still passing CI. I am working on isolating the issue.

**Comment by lipnikov** [comment]
Indeed, verbose output shows that dt is not going down when step is failing.

**Comment by nvohra0016** [comment]
@lipnikov Yes, right, and the time step reduction was being handled by CycleDriver? The negative height is being reported but the time step is not reducing.

**Comment by lipnikov** [comment]
@nvohra0016 CycleDriver is at a higher level compared to this test. If handling of dt is critical, you may consider converting this test to an MPC test.

**Comment by nvohra0016** [comment]
@lipnikov I am unsure if the issue here is the time step size. I ran the test again using an older branch (August 2022) and it seems to be working fine there.

**Comment by jd-moulton** [comment]
@nvohra0016 There was a significant update to the mesh infrastructure in September.   It's possible there is a bug there, or at least something changed in interface or behavior that is causing a problem for this test.   You may need to look closely just before and after that update to confirm, but then it is likely working with @lipnikov to debug the issue in the mesh infrastructure update.
