### ISSUE TITLE
Upgrade containers from focal (20.04) to jammy (22.04)

### ISSUE THREAD

**Issue by rfiorella** [amanzi/amanzi#778]
Support for Ubuntu 20.04 (focal fossa) ends in ~18 months (April 2025). This ticket holds information about testing on Ubuntu 22.04 (jammy jellyfish). Implementation testing on rfiorella/jammy-upgrade branch.

**Comment by rfiorella** [comment]
@jd-moulton @ecoon One thing that occurred to me this morning - do we want to run CI for both ubuntu versions in parallel for a little while? Wondering if it might be better to create a second CI workflow for 22.04 and just run them together for a few months rather than an abrupt switch, but curious to learn how you've approached these OS changes in the past.

**Comment by jd-moulton** [comment]
@rfiorella For now I would just switch it over to 22.04, and discard the 20.04 case.   At some point we may consider a longer list of OS versions, including things that are more common on institutional clusters (e.g., CentOS) to be a bit more comprehensive for folks.  But let's keep it simple for now as I think getting the multi-architecture problem resolved is a higher priority.
