### ISSUE TITLE
ic in all vis files?

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#816]
This change:

https://github.com/amanzi/amanzi/commit/78104df3133501474750ddd84a49ac6cb7829028#diff-5943c6109a10447e409ad4b7f332436bd60e1ecdba1713713316da39470f09f1L757

breaks ATS visualization, because now all vis files have a key "0ic" in their *_dat.h5 files instead of a key "0".

At least in ats_xdmf we rely on being able to do this:

`cycles` = list(sorted(file['varname'].keys(), key=int))`

which converts all keys to integers to get their cycle number and sorts by cycle.

Does this also break VisIt?

**Comment by ecoon** [comment]
Nevermind -- I missed that this was fixed, just needed to pull.

**Comment by lipnikov** [comment]
@ecoon Original capability to add suffix, like in 0ic, was lost, probably after the state upgrade. The current solution is ad hoc. Looks like the coordinator has no direct control of names of vis files.
