### ISSUE TITLE
"time step" vs "timestep"

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#865]
Amanzi & ATS currently use the following parameters:

"timestep controller type"
"timestep manager"

but also

"time step reduction factor"
"time step increase factor"
"initial time step [s]"
"max time step"

I'm working on this code now, and would like to pick one.  Does anyone have a strong preference?  Reason for picking one vs the other?

@lipnikov @jd-moulton @levuvietphong  @dasvyat @smolins @ghammond86

**Comment by lipnikov** [comment]
timestep. No reasons.
