### ISSUE TITLE
PFLOTRAN download link doesn't work in TPL build

### ISSUE THREAD

**Issue by rfiorella** [amanzi/amanzi#874]
Gitlab link to PFLOTRAN .tar.gz seems to be broken when bootstrap tries to download it, may also affect PETSc.

**Comment by jd-moulton** [comment]
There seem to be two problems.  

1.  the MD5SUM of the tarball has changed, meaning that gitlab repackaged the tagged release.  The contents should be the same, but we'll need to update our MD5SUMs for PFLOTRAN and PETSc.
2.  there is an error coming from the cmake command "Failure when receiving data from the peer", but the file downloads without any other issues.  It's this error that is stopping the build.

Worth testing on some other machines, and looking at older logs to see if this error showed up before.  

Work around for now is to update the MD5SUMS, and rerun boostrap.sh so it uses the files that were already downloaded. 


- The second

**Comment by jd-moulton** [comment]
Double checked the contents and md5sums.  So it appears the petsc tarball is the same and the error is just this new problem with the download.  For PFLOTRAN it is both, there was an update of the parameter defining the major version number (fixing 4 to 5).  So this really is a new tarball and needs a new md5sum.

**Comment by rfiorella** [comment]
After testing this, the link seems to be fine but the MD5 hash needs to be updated. (in fact, it fails for me when 'archive' is changed to 'tags'). Keeping in 'archive' in the path but updating the MD5 resolves the issue.
